// Industry / field-of-work options for the onboarding survey's searchable
// dropdown ("What field does your company work in?"). Kept as a flat list so the
// picker can filter by substring. Stored on the company as `survey.field`.
export const INDUSTRIES = [
  "Information Technology",
  "Software & SaaS",
  "Telecommunications",
  "Audio Visual & Systems Integration",
  "Electronics & Hardware",
  "Construction & Contracting",
  "Architecture & Interior Design",
  "Engineering Services",
  "Manufacturing",
  "Oil, Gas & Energy",
  "Utilities",
  "Real Estate & Property",
  "Facilities Management",
  "Retail & E-commerce",
  "Wholesale & Distribution",
  "Logistics & Supply Chain",
  "Transportation",
  "Automotive",
  "Aviation & Aerospace",
  "Hospitality & Tourism",
  "Food & Beverage",
  "Events & Entertainment",
  "Media & Advertising",
  "Marketing & PR",
  "Education & Training",
  "Healthcare & Medical",
  "Pharmaceuticals",
  "Banking & Financial Services",
  "Insurance",
  "Accounting & Auditing",
  "Legal Services",
  "Consulting & Professional Services",
  "Human Resources & Recruitment",
  "Government & Public Sector",
  "Non-Profit & NGO",
  "Agriculture",
  "Mining & Metals",
  "Textiles & Apparel",
  "Security & Defense",
  "Sports & Recreation",
  "Other",
];
