// THE PAGE SHAPE, ASSERTED AGAINST A RUNNING SERVER.
//
// Everything here is a property that cannot be checked by reading source. A
// component's `initial` prop becomes a style attribute only when something
// renders it; a redirect's status code exists only when something is asked; a
// heading is one text node or six hundred spans depending on what the framework
// emitted. Every defect below shipped past a green suite, two typecheckers and
// a build, because all four were reading the code rather than the answer.
//
// RUN IT AGAINST WHATEVER IS SERVING:
//
//   node tests/seo-live.mjs                       # http://localhost:3010
//   node tests/seo-live.mjs https://www.nompany.com
//
// It is NOT in `npm test`, deliberately: the suite runs without a server, and a
// test that silently passes when nothing is listening is worse than no test.
// It is the post-deploy check, and it becomes a CI gate when CI has a URL to
// point it at.

const BASE = (process.argv[2] || "http://localhost:3010").replace(/\/$/, "");
const LOCALES = ["en", "ar"];
// Every path the sitemap advertises. Kept in step with app/sitemap.js by the
// assertion below, which fetches the sitemap and compares.
const PATHS = ["", "/platform", "/pricing", "/security", "/about", "/contact", "/careers", "/terms", "/privacy"];

let fails = 0;
const ok = (label, cond, extra = "") => {
  if (!cond) fails += 1;
  console.log(`${cond ? "  ok  " : " FAIL "} ${label}${extra ? "  " + extra : ""}`);
};

const get = async (path, redirect = "follow") => {
  const res = await fetch(`${BASE}${path}`, { redirect, headers: { "user-agent": "nompany-seo-check" } });
  return { status: res.status, location: res.headers.get("location") || "", html: redirect === "follow" ? await res.text() : "" };
};

const count = (html, re) => (html.match(re) || []).length;
const textOf = (html, tag) => {
  const m = html.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`));
  return m ? m[1].replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim() : "";
};

console.log(`\n== ${BASE}\n`);

console.log("== every public page answers, once, with one heading");
for (const locale of LOCALES) {
  for (const path of PATHS) {
    const url = `/${locale}${path}`;
    const { status, html } = await get(url);
    ok(`${url} → 200`, status === 200, String(status));
    if (status !== 200) continue;

    // ONE H1, AND IT IS THE PAGE'S OWN. Two h1s is a page that cannot say what
    // it is about; none is a page that says nothing. The pricing route shipped
    // with none, because the heading component hardcoded `h2` and nobody had
    // rendered it as a page before.
    ok(`  one <h1>`, count(html, /<h1[\s>]/g) === 1, String(count(html, /<h1[\s>]/g)));

    // THE HEADING IS WORDS. The live site's h1 was split per character into
    // aria-hidden spans, so a tag-stripping extractor read it as separated
    // letters. A heading whose text survives tag-stripping as more than one
    // word is the property that was lost.
    const h1 = textOf(html, "h1");
    ok(`  <h1> reads as words`, h1.length > 3 && !/^(\S ){3,}/.test(h1), h1.slice(0, 48));

    // NOTHING THAT CARRIES TEXT STARTS INVISIBLE. `motion/react` writes a
    // component's `initial` into the server-rendered style attribute, so an
    // entrance beginning at opacity 0 ships the element hidden — and behind an
    // intersection observer it never resolves for anything that does not run
    // JavaScript. The home page's hero keeps a decorative mock that does this;
    // it is aria-hidden and is replaced by a real screenshot, so it is the one
    // allowance and it is bounded rather than open.
    const hidden = count(html, /opacity:0;/g);
    const allowance = path === "" ? 30 : 0;
    ok(`  no hidden content (≤${allowance})`, hidden <= allowance, `${hidden}`);

    // A TITLE AND A DESCRIPTION, PER PAGE PER LOCALE.
    ok(`  has a title`, textOf(html, "title").length > 5);
    ok(`  has a description`, /<meta name="description" content="[^"]{20,}"/.test(html));

    // SELF-REFERENCING CANONICAL, and reciprocal hreflang with x-default. The
    // two sides are generated by one helper so they cannot drift; this checks
    // the helper is actually reached on every page.
    ok(`  canonical is itself`, html.includes(`rel="canonical" href="${BASE}${url}"`)
      || html.includes(`rel="canonical" href="https://www.nompany.com${url}"`));
    // CASE-INSENSITIVE, and that is not laziness. React serialises the prop as
    // `hrefLang`, which is valid HTML — attribute names are case-insensitive —
    // and every engine parses it. A case-sensitive check here failed 48 times
    // against a site that was correct, which is the failure mode a live test
    // has to avoid hardest: an assertion that is wrong is worse than none,
    // because somebody will "fix" the page to satisfy it.
    ok(`  hreflang x-default`, /hreflang="x-default"/i.test(html));
    for (const other of LOCALES) ok(`  hreflang ${other}`, new RegExp(`hreflang="${other}"`, "i").test(html));

    // THE BRAND IS SPELLED ONE WAY. It was `nompany` in the metadata and
    // `Nompany` in the wordmark, twice on every page.
    ok(`  brand spelled one way`, !/Nompany/.test(html));

    // NO CLAIM THE PRODUCT CANNOT SUPPORT. Each of these was on the live page.
    for (const claim of ["180+", "99.99", "SSO/SCIM", "3.2M", "agentic workflows", "38 days"]) {
      ok(`  does not claim "${claim}"`, !html.includes(claim));
    }

    // NO LOCATION THE COMPANY DOES NOT HAVE. The Organization schema asserted a
    // Riyadh address on every page, machine-readable, for a company that has
    // never been there.
    ok(`  claims no address`, !/addressLocality/.test(html));
  }
}

console.log("\n== the prices are in the HTML");
{
  const { html } = await get("/en/pricing");
  // The measurement that started this rebuild: the string did not appear in the
  // served markup of a product with a published price list, because the figures
  // arrived from a client fetch.
  ok("SAR appears on the pricing page", count(html, /SAR/g) > 0, String(count(html, /SAR/g)));
  ok("...and an Offer is marked up", /"@type":"Offer"/.test(html));
}

console.log("\n== redirects say what they mean");
{
  const root = await get("/", "manual");
  ok("/ → 308 (permanent, not 307)", root.status === 308, String(root.status));
  ok("...to the locale root", /\/en\/?$/.test(root.location), root.location);

  for (const [from, to] of [["/features", "/en/platform"], ["/gallery", "/en"], ["/c/anything", "/en"]]) {
    const r = await get(from, "manual");
    ok(`${from} → 308`, r.status === 308, String(r.status));
    ok(`  → ${to}`, r.location.endsWith(to), r.location);
  }
}

console.log("\n== a wrong URL answers like a wrong URL");
for (const bad of ["/Not_A_Slug", "/x", "/wp-admin", "/index.php"]) {
  const r = await get(bad, "manual");
  // Not a 307 to a login screen: that tells a crawler the address exists and
  // is merely elsewhere, and tells a person to sign in for something that was
  // never there.
  ok(`${bad} → 404`, r.status === 404, String(r.status));
}

console.log("\n== the sitemap tells the truth");
{
  const a = await get("/sitemap.xml");
  const b = await get("/sitemap.xml");
  const lastmods = (s) => (s.match(/<lastmod>[^<]+<\/lastmod>/g) || []).join("|");
  // `lastModified` was `new Date()`, so two consecutive fetches disagreed and
  // every page claimed to have changed at the instant it was asked about.
  ok("two fetches agree on every lastmod", lastmods(a.html) === lastmods(b.html));
  ok("...and there is at least one", lastmods(a.html).length > 0);

  ok("login is not advertised", !a.html.includes("/login"));
  ok("signup is not advertised", !a.html.includes("/signup"));
  for (const p of PATHS) {
    ok(`lists /en${p}`, a.html.includes(`/en${p}</loc>`) || a.html.includes(`/en${p}"`) || a.html.includes(`>${BASE}/en${p}<`));
  }

  const login = await get("/en/login");
  ok("...and login says noindex", /noindex/.test(login.html));
}

console.log("\n== robots.txt");
{
  const r = await get("/robots.txt");
  ok("names the sitemap", r.html.includes("sitemap"));
  ok("keeps the app out", /Disallow: \/studio/.test(r.html) && /Disallow: \/api/.test(r.html));
  // The hero preview route was deleted; a disallow for a path that 404s is
  // clutter that outlives what it guarded.
  ok("...and disallows nothing that no longer exists", !/preview/.test(r.html));
}

console.log(fails ? `\n${fails} FAILED\n` : "\nseo-live: all passed\n");
process.exit(fails ? 1 : 0);
