import type { HelpModule } from "../types";

// NOVA'S HELP FOR THE SELLING DEPARTMENTS — Point of Sale and Marketing.
//
// CRM & SALES MOVED OUT, 27/09/2026, to `./crmSales.ts`, and QUOTATIONS the
// same day, to `./quotations.ts`: each one's entries became that department's
// chapter of the studio manual (see `../manual.ts`), and a module that is a
// chapter is written to that module's own ordering rules. Their entry ids did
// not change, and entries here still link to them by id.
//
// WRITTEN FROM `docs/functionality/*.md`. Where a doc lists something under "Not built yet" and a
// person would plausibly ask for it, the entry says in words that it is not
// available — a help desk that is silent about a gap reads as a feature nobody
// can find. When one of those ships, its entry changes in the same commit.
export const sales: HelpModule = {
  topics: [
    // ---- Point of Sale -------------------------------------------------------
    { id: "dept.pos", parent: "departments", sectionKey: "pos", order: 17,
      label: { en: "Point of Sale", ar: "نقطة البيع" },
      blurb: { en: "The counter: tills, shifts, receipts, returns and offers", ar: "الكاونتر: الصناديق والورديات والإيصالات والمرتجعات والعروض" } },
    { id: "dept.pos-till", parent: "dept.pos", sectionKey: "pos-till", order: 1,
      label: { en: "Till", ar: "الصندوق" },
      blurb: { en: "Selling at the counter, opening and closing a drawer", ar: "البيع على الكاونتر، وفتح الدرج وإغلاقه" } },
    { id: "dept.pos-sales", parent: "dept.pos", sectionKey: "pos-sales", order: 2,
      label: { en: "Sales", ar: "المبيعات" },
      blurb: { en: "Every receipt in a period, with downloads", ar: "كل الإيصالات في فترة، مع التنزيلات" } },
    { id: "dept.pos-shifts", parent: "dept.pos", sectionKey: "pos-shifts", order: 3,
      label: { en: "Shift history", ar: "سجل الورديات" },
      blurb: { en: "Every drawer opened, counted and closed", ar: "كل درج فتح وعد وأغلق" } },
    { id: "dept.pos-returns", parent: "dept.pos", sectionKey: "pos-returns", order: 4,
      label: { en: "Returns", ar: "المرتجعات" },
      blurb: { en: "Taking goods back and refunding the customer", ar: "استرجاع البضاعة ورد المبلغ للعميل" } },
    { id: "dept.pos-promotions", parent: "dept.pos", sectionKey: "pos-promotions", order: 5,
      label: { en: "Promotions", ar: "العروض" },
      blurb: { en: "Offers and coupons the till applies", ar: "العروض والقسائم التي يطبقها الصندوق" } },
    { id: "dept.pos-settings", parent: "dept.pos", sectionKey: "pos-settings", order: 6,
      label: { en: "Settings", ar: "الإعدادات" },
      blurb: { en: "Tills, device pairing, tax on shelf prices, receipt footer", ar: "الصناديق وربط الأجهزة والضريبة في سعر الرف وتذييل الإيصال" } },

    // ---- Marketing -----------------------------------------------------------
    { id: "dept.marketing", parent: "departments", sectionKey: "marketing", order: 18,
      label: { en: "Marketing", ar: "التسويق" },
      blurb: { en: "Campaigns, forms, spend, consent, events and partners", ar: "الحملات والنماذج والإنفاق والموافقات والفعاليات والشركاء" } },
    { id: "dept.marketing-campaigns", parent: "dept.marketing", sectionKey: "marketing-campaigns", order: 1,
      label: { en: "Campaigns", ar: "الحملات" },
      blurb: { en: "The campaign register, targets and leads sent to Sales", ar: "سجل الحملات والأهداف والعملاء المحتملون المرسلون إلى المبيعات" } },
    { id: "dept.marketing-forms", parent: "dept.marketing", sectionKey: "marketing-forms", order: 2,
      label: { en: "Forms", ar: "النماذج" },
      blurb: { en: "Public forms: enquiries, registrations and surveys", ar: "نماذج عامة: استفسارات وتسجيلات واستبيانات" } },
    { id: "dept.marketing-budget", parent: "dept.marketing", sectionKey: "marketing-budget", order: 3,
      label: { en: "Budget & spend", ar: "الميزانية والإنفاق" },
      blurb: { en: "What each campaign was allowed, spent and brought in", ar: "ما خصص لكل حملة وما أنفقته وما جلبته" } },
    { id: "dept.marketing-planning", parent: "dept.marketing", sectionKey: "marketing-planning", order: 4,
      label: { en: "Planning & calendar", ar: "التخطيط والتقويم" },
      blurb: { en: "Campaigns across the weeks, and plans by period", ar: "الحملات عبر الأسابيع، والخطط حسب الفترة" } },
    { id: "dept.marketing-audiences", parent: "dept.marketing", sectionKey: "marketing-audiences", order: 5,
      label: { en: "Audiences & consent", ar: "الجماهير والموافقات" },
      blurb: { en: "The consent ledger: who agreed to be contacted", ar: "سجل الموافقات: من وافق على التواصل معه" } },
    { id: "dept.marketing-events", parent: "dept.marketing", sectionKey: "marketing-events", order: 6,
      label: { en: "Events & webinars", ar: "الفعاليات والندوات" },
      blurb: { en: "Events, sign-ups and who actually came", ar: "الفعاليات والمسجلون ومن حضر فعلا" } },
    { id: "dept.marketing-content", parent: "dept.marketing", sectionKey: "marketing-content", order: 7,
      label: { en: "Content & brand assets", ar: "المحتوى وأصول العلامة" },
      blurb: { en: "Artwork, copy and logos, with their versions", ar: "التصاميم والنصوص والشعارات مع إصداراتها" } },
    { id: "dept.marketing-partners", parent: "dept.marketing", sectionKey: "marketing-partners", order: 8,
      label: { en: "Partners & influencers", ar: "الشركاء والمؤثرون" },
      blurb: { en: "Who sends you business, counted from their links", ar: "من يرسل إليك العمل، محسوبا من روابطهم" } },
  ],

  entries: [
    // =========================================================================
    // POINT OF SALE
    // =========================================================================
    { id: "pos.about", topic: "dept.pos", kind: "about", common: true, open: "pos",
      q: { en: "What is Point of Sale for?", ar: "ما الغرض من نقطة البيع؟" },
      a: { en: "Point of Sale is a till for a shop's walk-in customers: scan, basket, pay, print. It is general retail, designed around no single trade, and it works online only, so a till with no connection stops selling. Every sale takes the goods out of Inventory, which the studio must have. Beside the till are Sales, Shift history, Returns, Promotions and Settings, plus a dashboard of takings.",
           ar: "نقطة البيع صندوق لعملاء المتجر المباشرين: مسح، ثم سلة، ثم دفع، ثم طباعة. وهي مصممة للبيع بالتجزئة عموما دون التقيد بمجال بعينه، وتعمل عبر الإنترنت فقط، فالصندوق بلا اتصال يتوقف عن البيع. كل عملية بيع تخرج البضاعة من المخزون، ويجب أن يكون قسم المخزون موجودا لدى الاستوديو. وبجانب الصندوق توجد المبيعات وسجل الورديات والمرتجعات والعروض والإعدادات، إضافة إلى لوحة المتحصلات." },
      keywords: ["pos", "point of sale", "till", "cashier", "retail", "نقطة البيع", "كاشير", "صندوق", "متجر", "بيع بالتجزئة"],
      related: ["pos-till.about", "pos.dashboard"] },
    { id: "pos.dashboard", topic: "dept.pos", kind: "about", open: "pos",
      q: { en: "What does the Point of Sale dashboard show?", ar: "ماذا تعرض لوحة معلومات نقطة البيع؟" },
      a: { en: "For the period you choose (a day by default, or a week, month, quarter, half-year or year) it shows takings, number of sales, the average sale, units sold, tax and the drawers open now, plus offers running when you may see them. Everything sold lists every item with its units and value. Best sellers and takings by day are included depending on your plan, and Stock to reorder appears for whoever holds the stock alert. There is no comparison with the previous period yet.",
           ar: "تعرض للفترة التي تختارها (يوم افتراضيا، أو أسبوع أو شهر أو ربع أو نصف سنة أو سنة) المتحصلات وعدد المبيعات ومتوسط البيع والوحدات المباعة والضريبة والأدراج المفتوحة الآن، إضافة إلى العروض الجارية لمن يحق له رؤيتها. وتسرد قائمة كل ما بيع كل صنف بوحداته وقيمته. وتظهر الأصناف الأكثر مبيعا والمتحصلات اليومية حسب باقتك، وتظهر الأصناف الواجب إعادة طلبها لمن يملك تنبيه المخزون. ولا توجد بعد مقارنة بالفترة السابقة." },
      keywords: ["takings", "daily sales", "best sellers", "dashboard", "المتحصلات", "مبيعات اليوم", "الأكثر مبيعا", "لوحة المعلومات"],
      related: ["pos-sales.about"] },
    { id: "pos.till-limit", topic: "dept.pos", kind: "troubleshoot", open: "pos-settings",
      q: { en: "Why can't I add or pair another till?", ar: "لماذا لا أستطيع إضافة صندوق آخر أو ربطه؟" },
      a: { en: "Your plan sets how many tills the studio may have. A new or reactivated till, or a pairing, past that limit is refused with the number allowed. Retiring a till you no longer use frees its place; a larger allowance comes with a different package.",
           ar: "تحدد باقتك عدد الصناديق المسموح بها للاستوديو. ويرفض إضافة صندوق جديد أو إعادة تفعيل صندوق أو ربط جهاز إذا تجاوز ذلك الحد، مع ذكر العدد المسموح. إيقاف صندوق لم تعد تستخدمه يحرر مكانه، والحد الأكبر يأتي مع باقة أخرى." },
      keywords: ["till limit", "max tills", "upgrade", "package", "حد الصناديق", "ترقية", "الباقة"],
      related: ["pos-settings.tills"] },

    // ---- Till --------------------------------------------------------------
    { id: "pos-till.about", topic: "dept.pos-till", kind: "about", open: "pos-till",
      q: { en: "How does the till work?", ar: "كيف يعمل الصندوق؟" },
      a: { en: "The till opens on the device paired to it and keeps the scan box ready. A cashier opens a shift with the cash in the drawer, sells through the day and closes the shift by counting the drawer. The server prices every basket from the items, applies the shop's offers and checks the stock before the sale is written. Receipts print on an 80 mm printer from the browser, and a reprint reads exactly as the first.",
           ar: "يفتح الصندوق على الجهاز المرتبط به ويبقي خانة المسح جاهزة. يفتح الكاشير وردية بالنقد الموجود في الدرج، ويبيع طوال اليوم، ثم يغلق الوردية بعد عد الدرج. يسعر الخادم كل سلة من الأصناف ويطبق عروض المتجر ويتحقق من المخزون قبل تسجيل البيع. تطبع الإيصالات على طابعة 80 مم من المتصفح، وتطابق إعادة الطباعة الإيصال الأول تماما." },
      keywords: ["till", "cash register", "checkout", "sell", "الصندوق", "آلة الكاشير", "البيع", "المحاسبة"],
      related: ["pos-till.sell", "pos-till.shift"] },
    { id: "pos-till.sell", topic: "dept.pos-till", kind: "howto", common: true, open: "pos-till",
      q: { en: "How do I make a sale at the till?", ar: "كيف أجري عملية بيع في الصندوق؟" },
      a: { en: "Scan a barcode, or type part of a name or SKU; an exact code or name adds itself once you pause typing. Payment can be cash, card or transfer, split as needed, and only cash gives change. A customer who gives their phone number is recognised next time and registered as a customer; leave it blank for a walk-in. A card payment is recorded with a typed reference, because the till does not talk to card terminals yet.",
           ar: "امسح الباركود، أو اكتب جزءا من الاسم أو رمز الصنف؛ ويضاف الرمز أو الاسم المطابق تماما تلقائيا عند توقفك عن الكتابة. يمكن الدفع نقدا أو بالبطاقة أو بالتحويل، مع تقسيم الدفع عند الحاجة، والنقد وحده يعطي باقيا. العميل الذي يعطي رقم هاتفه يتعرف عليه في المرة التالية ويسجل عميلا؛ اتركه فارغا للعميل العابر. تسجل دفعة البطاقة بمرجع يكتب يدويا، لأن الصندوق لا يتصل بأجهزة البطاقات بعد." },
      steps: { en: ["Make sure a shift is open on this till.", "Scan or search each item and set the quantity.", "Optionally type the customer's phone number.", "Under Payment, enter cash, card or transfer; use Split the payment if needed.", "Press Complete the sale, then Print the receipt."],
               ar: ["تأكد من وجود وردية مفتوحة على هذا الصندوق.", "امسح كل صنف أو ابحث عنه وحدد الكمية.", "اكتب رقم هاتف العميل إن رغب.", "في قسم الدفع أدخل النقد أو البطاقة أو التحويل، واستخدم تقسيم الدفع عند الحاجة.", "اضغط إتمام البيع، ثم طباعة الإيصال."] },
      keywords: ["sell", "scan", "barcode", "payment", "split payment", "بيع", "باركود", "دفع", "إيصال", "تقسيم الدفع"],
      related: ["pos-till.refused", "pos-till.discount"] },
    { id: "pos-till.shift", topic: "dept.pos-till", kind: "howto", open: "pos-till",
      q: { en: "How do I open and close a shift?", ar: "كيف أفتح وردية وأغلقها؟" },
      a: { en: "A shift is a drawer's session on a till, and a till has one open shift at a time. Opening needs the right to sell; closing is a separate right. The shift report stores sales, tax by rate, takings by method, change given, the opening float, the expected cash, the counted cash and the difference, and discounts given. A short or over drawer is reported, never corrected.",
           ar: "الوردية جلسة درج على صندوق، وللصندوق وردية مفتوحة واحدة في كل مرة. فتحها يحتاج إلى صلاحية البيع، وإغلاقها صلاحية منفصلة. يحفظ تقرير الوردية المبيعات والضريبة حسب النسبة والمتحصلات حسب طريقة الدفع والباقي المعطى ورصيد الافتتاح والنقد المتوقع والنقد المعدود والفرق والخصومات الممنوحة. ويسجل نقص الدرج أو زيادته ولا يصحح أبدا." },
      steps: { en: ["Press Open a shift and enter the cash in the drawer to start.", "Sell through the day.", "At the end, press Close the shift.", "Count the drawer and enter the cash counted, with any notes.", "Print the report."],
               ar: ["اضغط فتح وردية وأدخل النقد الموجود في الدرج للبدء.", "بع طوال اليوم.", "في النهاية اضغط إغلاق الوردية.", "عد الدرج وأدخل النقد المعدود مع أي ملاحظات.", "اطبع التقرير."] },
      keywords: ["open shift", "close shift", "float", "count drawer", "end of day", "فتح وردية", "إغلاق وردية", "رصيد افتتاحي", "عد الدرج", "نهاية اليوم"],
      related: ["pos-shifts.about", "pos-shifts.over-short"] },
    { id: "pos-till.refused", topic: "dept.pos-till", kind: "troubleshoot", common: true, open: "pos-till",
      q: { en: "Why was my sale refused?", ar: "لماذا رفضت عملية البيع؟" },
      a: { en: "The till refuses a sale when no shift is open, when stock cannot cover the basket (it says how much is available and how much more is expired), or when the payments do not cover the total. A card or transfer for more than is due is refused, because only cash gives change. An item with no price is refused unless you may change prices. If the shop's offers changed since the basket was built, the till shows both totals and asks you to confirm.",
           ar: "يرفض الصندوق البيع إذا لم تكن هناك وردية مفتوحة، أو إذا لم يغط المخزون السلة (ويذكر الكمية المتاحة والكمية المنتهية الصلاحية)، أو إذا لم تغط المدفوعات الإجمالي. وترفض دفعة البطاقة أو التحويل التي تزيد على المستحق، لأن النقد وحده يعطي باقيا. ويرفض الصنف الذي لا سعر له إلا إذا كنت تملك صلاحية تغيير الأسعار. وإذا تغيرت عروض المتجر منذ بناء السلة يعرض الصندوق الإجماليين ويطلب تأكيدك." },
      keywords: ["sale refused", "out of stock", "not enough stock", "payment", "error", "رفض البيع", "نفاد المخزون", "خطأ", "الدفع"],
      related: ["pos-till.sell", "pos-till.discount"] },
    { id: "pos-till.discount", topic: "dept.pos-till", kind: "troubleshoot", open: "pos-till",
      q: { en: "Why can't I change a price or give a discount at the till?", ar: "لماذا لا أستطيع تغيير السعر أو منح خصم في الصندوق؟" },
      a: { en: "Changing a price or giving a discount is a separate right from selling. With it you can give a percentage or an amount on any line and one more on the whole basket. The studio may cap the largest discount a cashier may give, measured per line against the item's own price; whoever can change Point of Sale settings is not held to the cap. The shop's own offers come off first, and your discount is taken from what is left.",
           ar: "تغيير السعر أو منح خصم صلاحية منفصلة عن البيع. وبها يمكنك منح نسبة أو مبلغ على أي بند، وخصم إضافي على السلة كلها. وقد يحدد الاستوديو أكبر خصم يمنحه الكاشير، ويقاس لكل بند مقابل سعر الصنف نفسه، ولا يتقيد بهذا الحد من يملك صلاحية تغيير إعدادات نقطة البيع. تخصم عروض المتجر أولا، ثم يحسب خصمك مما تبقى." },
      keywords: ["discount", "price override", "change price", "discount limit", "خصم", "تغيير السعر", "حد الخصم"],
      related: ["pos-settings.discount-cap", "pos-promotions.about"] },
    { id: "pos-till.not-a-till", topic: "dept.pos-till", kind: "troubleshoot", open: "pos-settings",
      q: { en: "Why does it say this device is not a till?", ar: "لماذا تظهر رسالة بأن هذا الجهاز ليس صندوقا؟" },
      a: { en: "The till opens only on the device paired to it, with no exception for managers. A manager pairs a computer once, from that computer, in Point of Sale Settings with Pair this device. On a paired till, cashiers change with Switch cashier: they pick their name and type their personal PIN, and a cashier with no PIN sets one on their account's Security page. Five wrong PINs stop that person's PIN for fifteen minutes.",
           ar: "لا يفتح الصندوق إلا على الجهاز المرتبط به، دون استثناء للمديرين. يربط المدير الحاسوب مرة واحدة من الحاسوب نفسه، في إعدادات نقطة البيع عبر زر ربط هذا الجهاز. وعلى الصندوق المرتبط يتبادل الكاشيرون عبر زر تبديل الكاشير: يختار كل منهم اسمه ويكتب رمزه الشخصي، ومن لا رمز له يضبطه في صفحة الأمان في حسابه. وخمس محاولات خاطئة توقف رمز ذلك الشخص خمس عشرة دقيقة." },
      keywords: ["not a till", "pair device", "switch cashier", "pin", "wrong device", "جهاز غير مرتبط", "ربط الجهاز", "تبديل الكاشير", "الرمز السري"],
      related: ["pos-settings.pair"] },

    // ---- Sales -------------------------------------------------------------
    { id: "pos-sales.about", topic: "dept.pos-sales", kind: "about", common: true, open: "pos-sales",
      q: { en: "What is on the Point of Sale Sales screen?", ar: "ماذا تعرض شاشة مبيعات نقطة البيع؟" },
      a: { en: "Every sale in the period, newest first: receipt, date and time, till, cashier, units, how it was paid and total. You can search by receipt number or item and filter by till, cashier and payment method, and the totals follow the filter. The screen shows the newest 2,000 and says so; the download is not capped. A receipt is never edited or deleted.",
           ar: "كل عمليات البيع في الفترة، الأحدث أولا: الإيصال والتاريخ والوقت والصندوق والكاشير والوحدات وطريقة الدفع والإجمالي. يمكنك البحث برقم الإيصال أو الصنف والتصفية حسب الصندوق والكاشير وطريقة الدفع، وتتبع الإجماليات التصفية. تعرض الشاشة أحدث 2000 عملية وتذكر ذلك، أما التنزيل فبلا حد. ولا يعدل الإيصال ولا يحذف أبدا." },
      keywords: ["receipts", "sales list", "transactions", "الإيصالات", "قائمة المبيعات", "العمليات"],
      related: ["pos-sales.export", "pos-sales.reprint"] },
    { id: "pos-sales.export", topic: "dept.pos-sales", kind: "howto", common: true, open: "pos-sales",
      q: { en: "How do I download my till sales to Excel?", ar: "كيف أنزل مبيعات الصندوق إلى Excel؟" },
      a: { en: "Downloading is a right of its own. There are three CSV downloads, filtered exactly as the list is or limited to the receipts you tick: Sales (one row per receipt), Items sold totals (one row per item) and Items sold every line. Times are written in your own clock, and the files open correctly in Excel, Arabic included.",
           ar: "التنزيل صلاحية مستقلة. توجد ثلاثة تنزيلات بصيغة CSV، مصفاة تماما كالقائمة أو مقتصرة على الإيصالات التي تحددها: المبيعات (صف لكل إيصال)، وإجماليات الأصناف المباعة (صف لكل صنف)، وكل بنود الأصناف المباعة. تكتب الأوقات بتوقيتك، وتفتح الملفات بشكل صحيح في Excel بما فيها العربية." },
      steps: { en: ["Open Sales and choose the period.", "Filter by till, cashier or payment method, or tick receipts.", "Choose the download: Sales, Items sold (totals) or Items sold (every line)."],
               ar: ["افتح المبيعات واختر الفترة.", "صف حسب الصندوق أو الكاشير أو طريقة الدفع، أو حدد إيصالات.", "اختر التنزيل: المبيعات، أو الأصناف المباعة (إجماليات)، أو الأصناف المباعة (كل البنود)."] },
      keywords: ["export", "csv", "excel", "download", "report", "تصدير", "تنزيل", "إكسل", "تقرير"],
      related: ["pos-sales.about"] },
    { id: "pos-sales.reprint", topic: "dept.pos-sales", kind: "howto", open: "pos-sales",
      q: { en: "How do I reprint a receipt?", ar: "كيف أعيد طباعة إيصال؟" },
      a: { en: "Open the sale from the Sales list. It shows the slip exactly as it was stored, with the cashier and the shift, and you can reprint it from there. Sending a receipt by WhatsApp is not available yet.",
           ar: "افتح عملية البيع من قائمة المبيعات. تعرض الإيصال تماما كما حفظ، مع الكاشير والوردية، ويمكنك إعادة طباعته من هناك. إرسال الإيصال عبر واتساب غير متاح بعد." },
      steps: { en: ["Open Sales and find the receipt by number or item.","Open the sale.","Reprint it from there."],
               ar: ["افتح المبيعات وابحث عن الإيصال بالرقم أو الصنف.","افتح عملية البيع.","أعد طباعته من هناك."] },
      keywords: ["reprint", "copy receipt", "lost receipt", "whatsapp", "إعادة طباعة", "نسخة إيصال", "واتساب"],
      related: ["pos-sales.about"] },
    { id: "pos-sales.void", topic: "dept.pos-sales", kind: "troubleshoot", open: "pos-returns",
      q: { en: "Can I void or cancel a sale?", ar: "هل يمكنني إبطال عملية بيع أو إلغاؤها؟" },
      a: { en: "Not yet. A receipt is never edited or deleted, and voiding a sale or an exchange as one act is not available. To give money back, record a return against the receipt on the Returns screen.",
           ar: "ليس بعد. لا يعدل الإيصال ولا يحذف أبدا، وإبطال البيع أو الاستبدال كعملية واحدة غير متاحين. لرد المبلغ سجل مرتجعا على الإيصال من شاشة المرتجعات." },
      keywords: ["void", "cancel sale", "exchange", "undo sale", "إبطال", "إلغاء البيع", "استبدال"],
      related: ["pos-returns.howto"] },

    // ---- Shift history -----------------------------------------------------
    { id: "pos-shifts.about", topic: "dept.pos-shifts", kind: "about", common: true, open: "pos-shifts",
      q: { en: "What does Shift history show?", ar: "ماذا يعرض سجل الورديات؟" },
      a: { en: "Every drawer opened in the period, newest first: number, till, who opened and closed it and when, sales, takings, expected cash and the difference, with over or short. A closed shift shows the report stored at close; an open one shows its figures so far and says so. Each shift opens its printable report and its sales.",
           ar: "كل درج فتح في الفترة، الأحدث أولا: الرقم والصندوق ومن فتحه وأغلقه ومتى، والمبيعات والمتحصلات والنقد المتوقع والفرق مع الزيادة أو النقص. تعرض الوردية المغلقة التقرير المحفوظ عند الإغلاق، والمفتوحة أرقامها حتى الآن مع التنبيه بذلك. وتفتح كل وردية تقريرها القابل للطباعة ومبيعاتها." },
      keywords: ["shift history", "shift report", "z report", "end of day", "سجل الورديات", "تقرير الوردية", "تقرير نهاية اليوم"],
      related: ["pos-shifts.over-short", "pos-shifts.books"] },
    { id: "pos-shifts.over-short", topic: "dept.pos-shifts", kind: "about", open: "pos-shifts",
      q: { en: "How is expected cash worked out, and why is my drawer short or over?", ar: "كيف يحسب النقد المتوقع، ولماذا في الدرج نقص أو زيادة؟" },
      a: { en: "Expected cash is the opening float plus the cash taken, less the change given and less cash refunds paid from the drawer. The difference is what was counted minus what was expected, and it is reported, never corrected. Check the shift's sales and refunds on the Sales screen to find the gap.",
           ar: "النقد المتوقع هو رصيد الافتتاح مضافا إليه النقد المقبوض، مطروحا منه الباقي المعطى والمبالغ النقدية المستردة من الدرج. والفرق هو المعدود ناقص المتوقع، ويسجل ولا يصحح أبدا. راجع مبيعات الوردية ومرتجعاتها في شاشة المبيعات لتحديد مصدر الفرق." },
      keywords: ["cash short", "cash over", "difference", "expected cash", "reconcile drawer", "نقص النقد", "زيادة النقد", "الفرق", "مطابقة الدرج"],
      related: ["pos-till.shift"] },
    { id: "pos-shifts.books", topic: "dept.pos-shifts", kind: "about", open: "pos-shifts",
      q: { en: "Does a shift post to the accounts?", ar: "هل تسجل الوردية في الحسابات؟" },
      a: { en: "Yes. When a drawer is counted and closed, one journal entry is written for the whole shift from its stored report: money in by where it landed, revenue at the net and the tax, with till refunds reversed on their own lines. If the chart of accounts is missing an account or the period is locked, the close still stands and the reason is shown. The cost of the goods sold is not posted yet.",
           ar: "نعم. عند عد الدرج وإغلاقه يكتب قيد يومية واحد للوردية كلها من تقريرها المحفوظ: الأموال الواردة حسب مكانها، والإيراد بالصافي، والضريبة، مع عكس مرتجعات الصندوق في بنود مستقلة. وإذا نقص حساب في دليل الحسابات أو كانت الفترة مقفلة يبقى الإغلاق قائما ويعرض السبب. ولا تسجل تكلفة البضاعة المباعة بعد." },
      keywords: ["journal", "ledger", "accounting", "posting", "cost of sales", "قيد يومية", "دفتر الأستاذ", "المحاسبة", "تكلفة المبيعات"],
      related: ["pos-shifts.about"] },

    // ---- Returns -----------------------------------------------------------
    { id: "pos-returns.about", topic: "dept.pos-returns", kind: "about", common: true, open: "pos-returns",
      q: { en: "How do returns work in Point of Sale?", ar: "كيف تعمل المرتجعات في نقطة البيع؟" },
      a: { en: "A return finds the sale by its receipt, or an issued invoice by its reference, and asks how many of each line, why, and how the money goes back. Nothing moves when it is asked: every return waits for its approval on the Approvals page, and a waiting return reserves its units. A return under every limit the studio set goes straight through. Once approved, the units go back into stock and the refund is paid.",
           ar: "يبحث المرتجع عن البيع بإيصاله، أو عن فاتورة صادرة بمرجعها، ثم يسأل عن الكمية من كل بند والسبب وطريقة رد المبلغ. لا يتحرك شيء عند الطلب: فكل مرتجع ينتظر اعتماده في صفحة الموافقات، ويحجز المرتجع المنتظر وحداته. والمرتجع الذي يقل عن كل الحدود التي وضعها الاستوديو يمر مباشرة. وبعد الاعتماد تعود الوحدات إلى المخزون ويرد المبلغ." },
      keywords: ["return", "refund", "give money back", "مرتجع", "استرداد", "إرجاع", "رد المبلغ"],
      related: ["pos-returns.howto", "pos-returns.fields"] },
    { id: "pos-returns.howto", topic: "dept.pos-returns", kind: "howto", common: true, open: "pos-returns",
      q: { en: "How do I record a return?", ar: "كيف أسجل مرتجعا؟" },
      a: { en: "Roles that can open the till can ask for a return. The refund is what was paid for each line, discounts included, and returning everything refunds the sale's total and its tax exactly. The person who asked does not answer it, unless they are the Admin.",
           ar: "الأدوار التي تفتح الصندوق يمكنها طلب مرتجع. المبلغ المسترد هو ما دفع فعلا لكل بند بعد الخصومات، وإرجاع كل شيء يرد إجمالي البيع وضريبته بدقة. ولا يرد على الطلب من قدمه، إلا إذا كان المسؤول." },
      steps: { en: ["Open Returns and scan the receipt's barcode or type its number (or an invoice reference).", "Enter how many of each line come back.", "Give the reason, which is required.", "Choose cash, card or transfer, and for cash the till whose drawer pays.", "Send it; follow its approval on the Returns screen."],
               ar: ["افتح المرتجعات وامسح باركود الإيصال أو اكتب رقمه (أو مرجع الفاتورة).", "أدخل الكمية المرتجعة من كل بند.", "اذكر السبب، وهو مطلوب.", "اختر نقدا أو بطاقة أو تحويلا، وفي حالة النقد الصندوق الذي يدفع من درجه.", "أرسله وتابع اعتماده في شاشة المرتجعات."] },
      keywords: ["new return", "refund customer", "scan receipt", "مرتجع جديد", "استرداد للعميل", "مسح الإيصال"],
      related: ["pos-returns.refused"] },
    { id: "pos-returns.fields", topic: "dept.pos-returns", kind: "fields", open: "pos-returns",
      q: { en: "What do I need to process a return?", ar: "ما الذي أحتاجه لإجراء مرتجع؟" },
      a: { en: "A return starts from the original sale, so you need its receipt or invoice. A return against an invoice can also be a credit on the client's account; money goes back only up to what the client paid, and it raises a draft credit note that Finance issues.",
           ar: "يبدأ المرتجع من البيع الأصلي، فتحتاج إلى إيصاله أو فاتورته. ويمكن أن يكون المرتجع على فاتورة رصيدا في حساب العميل؛ ولا يرد المال إلا بقدر ما دفعه العميل، وينشئ إشعار دائن كمسودة تصدره المالية." },
      fields: { en: ["The receipt number or barcode, or an issued invoice's reference", "How many of each line are coming back", "The reason (required)", "How the money goes back: cash, card or transfer, or a credit on account for an invoice", "For a cash refund, the till whose drawer pays"],
                ar: ["رقم الإيصال أو الباركود، أو مرجع فاتورة صادرة", "الكمية المرتجعة من كل بند", "السبب (مطلوب)", "طريقة رد المبلغ: نقدا أو بطاقة أو تحويلا، أو رصيد في الحساب للفاتورة", "في الاسترداد النقدي، الصندوق الذي يدفع من درجه"] },
      keywords: ["receipt", "invoice return", "credit note", "credit on account", "إيصال", "مرتجع فاتورة", "إشعار دائن", "رصيد"],
      related: ["pos-returns.howto"] },
    { id: "pos-returns.refused", topic: "dept.pos-returns", kind: "troubleshoot", open: "pos-returns",
      q: { en: "Why can't a return be approved?", ar: "لماذا لا يمكن اعتماد المرتجع؟" },
      a: { en: "A cash refund comes out of a drawer, so approving it needs a shift open on the return's till. The approval also re-checks what is left to return, and two returns for the same last unit cannot both be approved. If nobody is named for returns in Approval settings, whoever could approve returns before, plus the owner and Admins, answer them.",
           ar: "الاسترداد النقدي يخرج من درج، فاعتماده يتطلب وردية مفتوحة على صندوق المرتجع. ويعيد الاعتماد التحقق مما تبقى قابلا للإرجاع، فلا يمكن اعتماد مرتجعين لآخر وحدة نفسها. وإذا لم يسم أحد للمرتجعات في إعدادات الموافقات فيرد عليها من كان يعتمد المرتجعات سابقا إضافة إلى المالك والمسؤولين." },
      keywords: ["cannot approve", "no shift", "return refused", "approval", "لا يمكن الاعتماد", "لا توجد وردية", "رفض المرتجع"],
      related: ["pos-returns.about"] },
    { id: "pos-returns.not-yet", topic: "dept.pos-returns", kind: "troubleshoot", open: "pos-returns",
      q: { en: "Can I take a return without a receipt, or print a return slip?", ar: "هل يمكنني قبول مرتجع دون إيصال، أو طباعة إيصال مرتجع؟" },
      a: { en: "Not yet. Returns without a receipt, return windows, restocking fees and a condition per line are not available; everything approved goes back on the shelf, and damaged goods are written off in Inventory. A printed return slip and a tax credit note for a returned till sale are not available either.",
           ar: "ليس بعد. المرتجعات دون إيصال ومهل الإرجاع ورسوم إعادة التخزين وحالة كل بند غير متاحة؛ فكل ما يعتمد يعود إلى الرف، وتشطب البضاعة التالفة من المخزون. كما لا تتوفر بعد طباعة إيصال المرتجع ولا إشعار دائن ضريبي لمرتجع بيع الصندوق." },
      keywords: ["no receipt", "return slip", "return window", "damaged", "بدون إيصال", "إيصال مرتجع", "مهلة الإرجاع", "تالف"],
      related: ["pos-returns.about"] },

    // ---- Promotions --------------------------------------------------------
    { id: "pos-promotions.about", topic: "dept.pos-promotions", kind: "about", common: true, open: "pos-promotions",
      q: { en: "What are Promotions?", ar: "ما هي العروض؟" },
      a: { en: "A promotion is the shop's own decision to charge less, which the till applies by itself or because a cashier chose it. It is kept apart from the cashier's discount: the offers come off first and are printed on their own line on the receipt. The screen has three tabs, Offers, Coupons and Report. Loyalty points and online selling are not available yet, so an offer's points or online channel takes nothing off.",
           ar: "العرض قرار المتجر نفسه بتخفيض السعر، يطبقه الصندوق تلقائيا أو لأن الكاشير اختاره. وهو منفصل عن خصم الكاشير: تخصم العروض أولا وتطبع في سطر مستقل في الإيصال. للشاشة ثلاثة تبويبات: العروض والقسائم والتقرير. نقاط الولاء والبيع عبر الإنترنت غير متاحين بعد، فنقاط العرض أو قناته الإلكترونية لا تخصم شيئا." },
      keywords: ["promotion", "offer", "deal", "sale price", "buy one get one", "loyalty", "عرض", "تخفيض", "اشتر واحدا واحصل", "ولاء"],
      related: ["pos-promotions.create", "pos-promotions.coupons"] },
    { id: "pos-promotions.create", topic: "dept.pos-promotions", kind: "howto", open: "pos-promotions",
      q: { en: "How do I create an offer?", ar: "كيف أنشئ عرضا؟" },
      a: { en: "An offer starts from one of five presets: Buy X get Y, percentage off a type or a supplier, spend and save, a fixed price for a bundle, or coupon only; Advanced shows everything. The preview runs the real pricing on a sample basket and says why when it earns nothing. Schedules read the studio's time zone, and an offer can be limited to particular tills. Offers are never deleted; one that is no longer needed is ended or archived.",
           ar: "يبدأ العرض من أحد خمسة قوالب: اشتر كذا واحصل على كذا، ونسبة خصم على نوع أو مورد، وأنفق ووفر، وسعر ثابت لحزمة، وقسيمة فقط؛ ويعرض الخيار المتقدم كل الإعدادات. تشغل المعاينة التسعير الفعلي على سلة تجريبية وتوضح السبب إذا لم تستحق شيئا. تعتمد الجداول الزمنية على المنطقة الزمنية للاستوديو، ويمكن قصر العرض على صناديق محددة. لا تحذف العروض أبدا؛ فالعرض الذي لم يعد مطلوبا ينهى أو يؤرشف." },
      steps: { en: ["Open Promotions, Offers tab, and start a new offer.", "Choose a preset, or Advanced.", "Set the conditions, the benefit, the dates and any caps.", "Check the preview.", "Save it as a draft, then activate it."],
               ar: ["افتح العروض، تبويب العروض، وابدأ عرضا جديدا.", "اختر قالبا أو الخيار المتقدم.", "حدد الشروط والميزة والتواريخ وأي حدود.", "تحقق من المعاينة.", "احفظه كمسودة ثم فعله."] },
      keywords: ["new offer", "create promotion", "bogo", "bundle", "schedule", "عرض جديد", "إنشاء عرض", "حزمة", "جدولة"],
      related: ["pos-promotions.activate", "pos-promotions.not-applied"] },
    { id: "pos-promotions.activate", topic: "dept.pos-promotions", kind: "troubleshoot", open: "pos-promotions",
      q: { en: "Why can't I edit an active offer, or why is my activation waiting?", ar: "لماذا لا أستطيع تعديل عرض نشط، أو لماذا ينتظر التفعيل؟" },
      a: { en: "An active offer is not edited: pause it, change it and put it back, and each step is logged. Going live needs a signature, because activation is what spends money; the steps and limits are set for promotions in Approval settings. An offer with no cap on its uses or per-sale amount could cost any amount, so it walks every approval step. A refused activation leaves the offer as a draft to rewrite.",
           ar: "لا يعدل العرض النشط: أوقفه مؤقتا ثم عدله ثم أعده، وتسجل كل خطوة. ويحتاج التفعيل إلى توقيع لأنه ما ينفق المال، وتضبط الخطوات والحدود للعروض في إعدادات الموافقات. والعرض الذي لا حد لعدد استخداماته أو لمبلغه في البيع الواحد قد يكلف أي مبلغ، فيمر بكل خطوات الاعتماد. والتفعيل المرفوض يبقي العرض مسودة لإعادة كتابته." },
      keywords: ["activate", "approval", "pause", "edit offer", "تفعيل", "اعتماد", "إيقاف مؤقت", "تعديل العرض"],
      related: ["pos-promotions.create"] },
    { id: "pos-promotions.coupons", topic: "dept.pos-promotions", kind: "about", open: "pos-promotions",
      q: { en: "How do coupons work?", ar: "كيف تعمل القسائم؟" },
      a: { en: "A coupon is its own record that unlocks an offer: a code on a poster, a code for one customer, or a batch of thousands. Every coupon needs a customer at the till, public ones included, so the cashier is asked for one before typing the code. A single-use code can be spent only once, and a code is cancelled, never deleted.",
           ar: "القسيمة سجل مستقل يفعل عرضا: رمز على ملصق، أو رمز لعميل واحد، أو دفعة من الآلاف. وتحتاج كل قسيمة إلى عميل في الصندوق، بما فيها القسائم العامة، فيطلب من الكاشير تحديد العميل قبل كتابة الرمز. ولا يستخدم الرمز أحادي الاستخدام إلا مرة واحدة، ويلغى الرمز ولا يحذف." },
      keywords: ["coupon", "voucher", "promo code", "discount code", "قسيمة", "كوبون", "رمز خصم", "رمز ترويجي"],
      related: ["pos-promotions.about"] },
    { id: "pos-promotions.not-applied", topic: "dept.pos-promotions", kind: "troubleshoot", common: true, open: "pos-promotions",
      q: { en: "Why didn't an offer apply at the till?", ar: "لماذا لم يطبق العرض في الصندوق؟" },
      a: { en: "An offer prices a basket only while it is active, inside its dates and schedule, on a till it names, and under its caps. Some offers wait for the cashier to choose them or for a coupon. Past its end date an offer prices nothing whatever its status says. The till does not see usage counters, so a spent cap is refused at the sale and the cashier confirms the new total.",
           ar: "لا يسعر العرض السلة إلا ما دام نشطا وضمن تواريخه وجدوله وعلى صندوق يذكره ودون حدوده. وبعض العروض تنتظر أن يختارها الكاشير أو قسيمة. وبعد تاريخ انتهائه لا يسعر العرض شيئا مهما كانت حالته. لا يرى الصندوق عدادات الاستخدام، فيرفض الحد المستنفد عند البيع ويؤكد الكاشير الإجمالي الجديد." },
      keywords: ["offer not working", "promotion not applied", "expired offer", "العرض لا يعمل", "لم يطبق العرض", "عرض منتهي"],
      related: ["pos-promotions.create", "pos-settings.discount-cap"] },
    { id: "pos-promotions.package", topic: "dept.pos-promotions", kind: "troubleshoot", open: "pos-promotions",
      q: { en: "Why can't I create promotions or coupons?", ar: "لماذا لا أستطيع إنشاء عروض أو قسائم؟" },
      a: { en: "Promotions, and separately coupons, tiers and schedules, are sold with your package. If your package does not include them, you cannot write new ones, but existing offers keep running and charging correctly. Writing offers also needs the right to create or edit promotions; choosing or removing an offer at the counter is a separate right.",
           ar: "العروض، وبشكل منفصل القسائم والشرائح والجداول الزمنية، تباع ضمن باقتك. وإذا لم تشملها باقتك فلا يمكنك كتابة عروض جديدة، لكن العروض الموجودة تستمر وتحتسب بشكل صحيح. كما تتطلب كتابة العروض صلاحية إنشاء العروض أو تعديلها، واختيار العرض أو إزالته عند الكاونتر صلاحية منفصلة." },
      keywords: ["package", "plan", "not allowed", "coupons locked", "الباقة", "غير مسموح", "القسائم مقفلة"],
      related: ["pos-promotions.about"] },

    // ---- Settings ----------------------------------------------------------
    { id: "pos-settings.about", topic: "dept.pos-settings", kind: "about", common: true, open: "pos-settings",
      q: { en: "What can I set in Point of Sale settings?", ar: "ما الذي يمكنني ضبطه في إعدادات نقطة البيع؟" },
      a: { en: "The tills (add, retire, use again, pair and unpair a device), whether shelf prices include tax, the receipt footer, the largest discount a cashier may give, and how soon an offer counts as ending soon. Viewing and editing settings are separate rights. The till itself is reached from the sidebar.",
           ar: "الصناديق (إضافة وإيقاف وإعادة استخدام وربط جهاز وفك ربطه)، وهل تشمل أسعار الرف الضريبة، وتذييل الإيصال، وأكبر خصم يمنحه الكاشير، ومتى يعد العرض قريب الانتهاء. عرض الإعدادات وتعديلها صلاحيتان منفصلتان. ويفتح الصندوق نفسه من القائمة الجانبية." },
      keywords: ["pos settings", "receipt footer", "tax included", "إعدادات نقطة البيع", "تذييل الإيصال", "شامل الضريبة"],
      related: ["pos-settings.tills", "pos-settings.tax"] },
    { id: "pos-settings.tills", topic: "dept.pos-settings", kind: "howto", open: "pos-settings",
      q: { en: "How do I add or retire a till?", ar: "كيف أضيف صندوقا أو أوقفه؟" },
      a: { en: "Each till has a name and a unique Till ID (TILL-01 unless you type one). A till is never deleted, because its receipts name it: it is retired instead, which also unpairs it, and it cannot be retired while it has a shift open. The number of tills is limited by your plan.",
           ar: "لكل صندوق اسم ومعرف فريد (TILL-01 ما لم تكتب غيره). لا يحذف الصندوق أبدا لأن إيصالاته تذكره، بل يوقف، وهذا يفك ربطه أيضا، ولا يمكن إيقافه ما دامت لديه وردية مفتوحة. وعدد الصناديق محدود بباقتك." },
      steps: { en: ["Open Point of Sale Settings.", "Press Add a till, type its name and optionally a Till ID, and save.", "To stop using one, press Retire; Use again brings it back."],
               ar: ["افتح إعدادات نقطة البيع.", "اضغط إضافة صندوق، واكتب اسمه ومعرفه اختياريا، ثم احفظ.", "لإيقاف صندوق اضغط إيقاف، وزر الاستخدام مجددا يعيده."] },
      keywords: ["add till", "new till", "retire till", "till id", "إضافة صندوق", "صندوق جديد", "إيقاف صندوق"],
      related: ["pos.till-limit", "pos-settings.pair"] },
    { id: "pos-settings.pair", topic: "dept.pos-settings", kind: "howto", common: true, open: "pos-settings",
      q: { en: "How do I pair a computer to a till?", ar: "كيف أربط حاسوبا بصندوق؟" },
      a: { en: "A manager pairs a device to a till once, from that device, and needs the right to edit Point of Sale settings. There is one device per till: pairing another replaces the first. Unpair works from any device, for a lost or replaced counter computer, and a device can also unpair itself from the cashier screen.",
           ar: "يربط المدير الجهاز بالصندوق مرة واحدة من الجهاز نفسه، ويحتاج إلى صلاحية تعديل إعدادات نقطة البيع. لكل صندوق جهاز واحد: ربط جهاز آخر يحل محل الأول. ويعمل فك الربط من أي جهاز في حالة فقدان حاسوب الكاونتر أو استبداله، ويمكن للجهاز أيضا فك ربط نفسه من شاشة الكاشير." },
      steps: { en: ["On the counter computer, sign in and open Point of Sale Settings.", "Find the till in the list.", "Press Pair this device; the list marks it as This device.", "Open the till from the sidebar."],
               ar: ["على حاسوب الكاونتر، سجل الدخول وافتح إعدادات نقطة البيع.", "ابحث عن الصندوق في القائمة.", "اضغط ربط هذا الجهاز، وستعلمه القائمة بأنه هذا الجهاز.", "افتح الصندوق من القائمة الجانبية."] },
      keywords: ["pair", "unpair", "device", "counter computer", "ربط", "فك الربط", "جهاز", "حاسوب الكاونتر"],
      related: ["pos-till.not-a-till"] },
    { id: "pos-settings.tax", topic: "dept.pos-settings", kind: "settings", open: "pos-settings",
      q: { en: "What does Shelf prices include tax do?", ar: "ماذا يعني خيار «أسعار الرف تشمل الضريبة»؟" },
      a: { en: "On, the item's sell price is what the customer pays and the tax is taken out of it: 11.50 at 15% is 10.00 plus 1.50. Off, tax is added at the till, as with a US sales tax. The default follows the studio's country.",
           ar: "عند تفعيله يكون سعر بيع الصنف هو ما يدفعه العميل وتستخرج الضريبة منه: 11.50 بنسبة 15% تساوي 10.00 مضافا إليها 1.50. وعند إيقافه تضاف الضريبة في الصندوق، كما في ضريبة المبيعات الأمريكية. والقيمة الافتراضية تتبع دولة الاستوديو." },
      keywords: ["vat included", "tax inclusive", "shelf price", "شامل الضريبة", "ضريبة القيمة المضافة", "سعر الرف"],
      related: ["pos-settings.about"] },
    { id: "pos-settings.discount-cap", topic: "dept.pos-settings", kind: "settings", open: "pos-settings",
      q: { en: "How do I limit cashier discounts and the ending-soon warning?", ar: "كيف أحدد خصومات الكاشير وتنبيه قرب انتهاء العروض؟" },
      a: { en: "Largest discount a cashier may give is a percentage measured on each line against the item's own price, counting a typed price, the line's discount and its share of a basket discount together; leave it blank for no limit. Whoever can change this setting is not held to it. How many days before its end an offer counts as ending soon is also set here, seven by default.",
           ar: "أكبر خصم يمنحه الكاشير نسبة تقاس لكل بند مقابل سعر الصنف نفسه، مع احتساب السعر المكتوب وخصم البند وحصته من خصم السلة معا؛ اتركه فارغا لعدم وضع حد. ولا يتقيد به من يملك صلاحية تغيير هذا الإعداد. كما يضبط هنا عدد الأيام التي يعد فيها العرض قريب الانتهاء قبل نهايته، وهو سبعة أيام افتراضيا." },
      keywords: ["discount cap", "max discount", "ending soon", "warning days", "حد الخصم", "أقصى خصم", "قرب الانتهاء"],
      related: ["pos-till.discount"] },

    // =========================================================================
    // MARKETING
    // =========================================================================
    { id: "marketing.about", topic: "dept.marketing", kind: "about", common: true, open: "marketing",
      q: { en: "What is Marketing for?", ar: "ما الغرض من قسم التسويق؟" },
      a: { en: "Marketing records the company's marketing work: campaigns with their budgets and targets, public forms, spend read from Finance, the consent ledger, a calendar and plans by period, events, brand assets and partners. The campaign is the parent of everything else. Leads stay Sales tickets: a campaign or a form sends them to Sales, and Marketing reads back what they became. nompany records marketing work but does not send it.",
           ar: "يسجل قسم التسويق العمل التسويقي للشركة: الحملات بميزانياتها وأهدافها، والنماذج العامة، والإنفاق المقروء من المالية، وسجل الموافقات، والتقويم والخطط حسب الفترة، والفعاليات، وأصول العلامة، والشركاء. والحملة هي الأصل لكل ما عداها. ويبقى العملاء المحتملون تذاكر مبيعات: ترسلهم الحملة أو النموذج إلى المبيعات، ويقرأ التسويق ما آلوا إليه. يسجل nompany العمل التسويقي لكنه لا ينفذ الإرسال." },
      keywords: ["marketing", "campaigns", "leads", "التسويق", "الحملات", "عملاء محتملون"],
      related: ["marketing-campaigns.about", "marketing.not-sending"] },
    { id: "marketing.dashboard", topic: "dept.marketing", kind: "about", open: "marketing",
      q: { en: "What does the Marketing dashboard show?", ar: "ماذا تعرض لوحة معلومات التسويق؟" },
      a: { en: "Six figures: campaigns running now, starting this week, needing attention, the budget in open campaigns, leads from campaigns against their target, and won value from campaigns against expected revenue. Then what needs somebody, campaigns by status, what is running now and open campaigns by channel. Its budget figure is what was planned; actual spend is on the Budget & spend screen. ROI, cost per lead and a marketing funnel are not on the dashboard yet.",
           ar: "ستة أرقام: الحملات الجارية الآن، والتي تبدأ هذا الأسبوع، والتي تحتاج إلى متابعة، والميزانية في الحملات المفتوحة، والعملاء المحتملون من الحملات مقابل هدفهم، وقيمة الفوز من الحملات مقابل الإيراد المتوقع. ثم ما يحتاج إلى متابعة، والحملات حسب الحالة، وما يجري الآن، والحملات المفتوحة حسب القناة. رقم الميزانية فيها هو المخطط له، أما الإنفاق الفعلي ففي شاشة الميزانية والإنفاق. ولا يتوفر بعد على اللوحة العائد على الاستثمار وتكلفة العميل المحتمل وقمع التسويق." },
      keywords: ["dashboard", "roi", "marketing figures", "لوحة المعلومات", "العائد على الاستثمار", "أرقام التسويق"],
      related: ["marketing-budget.about"] },
    { id: "marketing.not-sending", topic: "dept.marketing", kind: "troubleshoot", common: true, open: "marketing",
      q: { en: "Can nompany send emails, SMS or WhatsApp, or post to social media and ads?", ar: "هل يرسل nompany رسائل بريد أو نصية أو واتساب، أو ينشر على التواصل الاجتماعي والإعلانات؟" },
      a: { en: "No. nompany sends nothing, posts nothing and imports no ad data: companies use their own email and SMS tools for now, and linking a studio's social accounts is not available. Journeys, landing pages, lists and segments, and loyalty points are not available yet either. What you spend on those tools reaches Marketing as a supplier bill naming the campaign.",
           ar: "لا. لا يرسل nompany أي رسائل ولا ينشر ولا يستورد بيانات الإعلانات: تستخدم الشركات حاليا أدواتها الخاصة للبريد والرسائل النصية، وربط حسابات التواصل الاجتماعي للاستوديو غير متاح. كما لا تتوفر بعد رحلات العملاء وصفحات الهبوط والقوائم والشرائح ونقاط الولاء. وما تنفقه على تلك الأدوات يصل إلى التسويق كفاتورة مورد تذكر الحملة." },
      keywords: ["email", "sms", "whatsapp", "social media", "ads", "بريد إلكتروني", "رسائل نصية", "واتساب", "تواصل اجتماعي", "إعلانات"],
      related: ["marketing-budget.file-cost", "marketing-audiences.not-yet"] },

    // ---- Campaigns ---------------------------------------------------------
    { id: "marketing-campaigns.about", topic: "dept.marketing-campaigns", kind: "about", common: true, open: "marketing-campaigns",
      q: { en: "What is a campaign and what does its card show?", ar: "ما هي الحملة وماذا تعرض بطاقتها؟" },
      a: { en: "A campaign is a piece of marketing work with an objective, channels, dates, an owner, a budget and targets for leads, customers and revenue. Its card shows each target against what the campaign actually brought in, counted from the Sales tickets that name it: leads, deals won and won value. A campaign may be part of a top-level campaign, one level deep. Needs attention flags a late start, an overrun, or a start within seven days.",
           ar: "الحملة عمل تسويقي له هدف وقنوات وتواريخ ومسؤول وميزانية وأهداف للعملاء المحتملين والعملاء والإيراد. تعرض بطاقتها كل هدف مقابل ما جلبته الحملة فعلا، محسوبا من تذاكر المبيعات التي تذكرها: العملاء المحتملون والصفقات الرابحة وقيمتها. ويمكن أن تكون الحملة جزءا من حملة رئيسية بمستوى واحد فقط. وتنبه علامة «تحتاج إلى متابعة» إلى تأخر البدء أو تجاوز النهاية أو بدء خلال سبعة أيام." },
      keywords: ["campaign", "targets", "sub-campaign", "objective", "حملة", "أهداف", "حملة فرعية", "الهدف"],
      related: ["marketing-campaigns.fields", "marketing-campaigns.ladder"] },
    { id: "marketing-campaigns.fields", topic: "dept.marketing-campaigns", kind: "fields", open: "marketing-campaigns",
      q: { en: "What information do I need to create a campaign?", ar: "ما المعلومات التي أحتاجها لإنشاء حملة؟" },
      a: { en: "Campaigns are referenced CMP-0001 and so on, and creating one needs the right to create campaigns. A budget or target left blank is stored as not set rather than zero, and is not added up. Choosing an owner other than yourself needs the right to assign campaigns, and the owner is notified. The brief is four questions: who it is for, what you are saying, what you are offering, and what would make it a success.",
           ar: "ترقم الحملات بالشكل CMP-0001 وهكذا، ويحتاج إنشاؤها إلى صلاحية إنشاء الحملات. الميزانية أو الهدف المتروك فارغا يحفظ على أنه غير محدد لا صفرا، ولا يدخل في المجاميع. واختيار مسؤول غيرك يحتاج إلى صلاحية إسناد الحملات، ويبلغ المسؤول. أما الموجز فهو أربعة أسئلة: لمن الحملة، وماذا نقول، وماذا نعرض، وما الذي يجعلها ناجحة." },
      fields: { en: ["Name and description", "Objective: awareness, leads, sales, product launch, retention, event or other", "Channels, such as email, social, paid search, events or print", "Start and end dates", "Owner", "Budget, and targets for leads, customers and revenue (optional)", "Parent campaign and plan (optional)", "Landing page address and UTM tags (optional)", "Lead deadline in hours, 1 to 168 (optional)"],
                ar: ["الاسم والوصف", "الهدف: التوعية أو العملاء المحتملون أو المبيعات أو إطلاق منتج أو الاحتفاظ بالعملاء أو فعالية أو غير ذلك", "القنوات، مثل البريد والتواصل الاجتماعي والبحث المدفوع والفعاليات والمطبوعات", "تاريخا البدء والانتهاء", "المسؤول", "الميزانية وأهداف العملاء المحتملين والعملاء والإيراد (اختياري)", "الحملة الأم والخطة (اختياري)", "عنوان صفحة الهبوط ووسوم UTM (اختياري)", "مهلة العميل المحتمل بالساعات من 1 إلى 168 (اختياري)"] },
      keywords: ["new campaign", "create campaign", "budget", "brief", "حملة جديدة", "إنشاء حملة", "ميزانية", "موجز"],
      related: ["marketing-campaigns.tracked-link", "marketing-campaigns.about"] },
    { id: "marketing-campaigns.ladder", topic: "dept.marketing-campaigns", kind: "about", open: "marketing-campaigns",
      q: { en: "How does a campaign move through its statuses?", ar: "كيف تنتقل الحملة بين حالاتها؟" },
      a: { en: "Draft and Planned move either way; Planned goes to Running, which can be Paused and resumed; Running goes to Completed. Cancelled can be reached from any of those four. Running cannot go back to Planned, and Completed and Cancelled are final. Run again makes a Draft copy with no dates and no history, so two runs do not report as one.",
           ar: "تنتقل الحملة بين المسودة والمخططة في الاتجاهين، ومن المخططة إلى الجارية، ويمكن إيقاف الجارية مؤقتا واستئنافها، ومن الجارية إلى المكتملة. ويمكن الإلغاء من أي من هذه الأربع. لا تعود الجارية إلى مخططة، والمكتملة والملغاة نهائيتان. ويصنع زر «تشغيل مجددا» نسخة مسودة بلا تواريخ ولا سجل، حتى لا يحتسب التشغيلان كتشغيل واحد." },
      keywords: ["status", "running", "paused", "run again", "clone", "الحالة", "جارية", "متوقفة", "مكتملة", "تشغيل مجددا"],
      related: ["marketing-campaigns.delete"] },
    { id: "marketing-campaigns.send-lead", topic: "dept.marketing-campaigns", kind: "howto", common: true, open: "marketing-campaigns",
      q: { en: "How do I send a lead from a campaign to Sales?", ar: "كيف أرسل عميلا محتملا من حملة إلى المبيعات؟" },
      a: { en: "You need the right to edit campaigns, and Sales must be switched on. The lead arrives in Sales as a ticket at Lead, assigned to nobody, naming the campaign as its source and carrying the campaign's lead deadline; everybody who assigns leads is told it is waiting. Marketing cannot see which executive has a lead beyond the counts on the campaign.",
           ar: "تحتاج إلى صلاحية تعديل الحملات، ويجب أن يكون قسم المبيعات مفعلا. يصل العميل المحتمل إلى المبيعات كتذكرة في مرحلة عميل محتمل غير مسندة، تذكر الحملة مصدرا لها وتحمل مهلة العميل المحتمل الخاصة بالحملة، ويبلغ كل من يسند العملاء المحتملين بأنه ينتظر. ولا يستطيع التسويق رؤية المندوب المسؤول عن العميل المحتمل سوى الأعداد على الحملة." },
      steps: { en: ["On the campaign card, press Send a lead to Sales.", "Enter the person or company and a contact name.", "Give a phone or an email (at least one).", "Say what they want and add notes.", "Send."],
               ar: ["في بطاقة الحملة اضغط إرسال عميل محتمل إلى المبيعات.", "أدخل الشخص أو الشركة واسم جهة الاتصال.", "أدخل هاتفا أو بريدا إلكترونيا (أحدهما على الأقل).", "اذكر ما يريدون وأضف ملاحظات.", "أرسل."] },
      keywords: ["send lead", "lead to sales", "handover", "إرسال عميل محتمل", "تسليم للمبيعات"],
      related: ["crm-sales-tickets.assign-lead"] },
    { id: "marketing-campaigns.tracked-link", topic: "dept.marketing-campaigns", kind: "howto", open: "marketing-campaigns",
      q: { en: "How do I get a tracked link (UTM) for a campaign?", ar: "كيف أحصل على رابط متتبع (UTM) لحملة؟" },
      a: { en: "Give the campaign a landing page address (http or https) and the five UTM tags, and the register shows the link with the tags added, with a Copy button. If utm_campaign is blank, the campaign's name is used. When somebody arrives at one of your forms through such a link, the reply records the tags and the campaign on the link gets the credit.",
           ar: "أعط الحملة عنوان صفحة هبوط (http أو https) ووسوم UTM الخمسة، فيعرض السجل الرابط مع الوسوم المضافة وزر نسخ. وإذا ترك utm_campaign فارغا يستخدم اسم الحملة. وعندما يصل أحدهم إلى أحد نماذجك عبر هذا الرابط، يسجل الرد الوسوم وتنسب النتيجة إلى الحملة المذكورة في الرابط." },
      steps: { en: ["Edit the campaign.","Enter the landing page address and the UTM tags.","Save, then press Copy beside the tagged link on the register."],
               ar: ["عدل الحملة.","أدخل عنوان صفحة الهبوط ووسوم UTM.","احفظ، ثم اضغط نسخ بجانب الرابط الموسوم في السجل."] },
      keywords: ["utm", "tracking link", "landing page", "attribution", "رابط متتبع", "صفحة هبوط", "إسناد المصدر"],
      related: ["marketing-partners.about", "marketing-forms.about"] },
    { id: "marketing-campaigns.delete", topic: "dept.marketing-campaigns", kind: "troubleshoot", open: "marketing-campaigns",
      q: { en: "Why can't I delete or edit a campaign?", ar: "لماذا لا أستطيع حذف حملة أو تعديلها؟" },
      a: { en: "Only a Draft, Planned or Cancelled campaign can be deleted, and never one with sub-campaigns; one that ran is kept as the record of what ran. A Completed or Cancelled campaign is final and is no longer edited. Use Run again to start a new copy.",
           ar: "لا تحذف إلا الحملة المسودة أو المخططة أو الملغاة، ولا تحذف أبدا حملة لها حملات فرعية؛ فالحملة التي جرت تبقى سجلا لما جرى. والحملة المكتملة أو الملغاة نهائية ولا تعدل بعدها. استخدم «تشغيل مجددا» لبدء نسخة جديدة." },
      keywords: ["delete campaign", "cannot edit", "completed", "حذف حملة", "لا يمكن التعديل", "مكتملة"],
      related: ["marketing-campaigns.ladder"] },

    // ---- Forms -------------------------------------------------------------
    { id: "marketing-forms.about", topic: "dept.marketing-forms", kind: "about", common: true, open: "marketing-forms",
      q: { en: "What are Marketing forms?", ar: "ما هي نماذج التسويق؟" },
      a: { en: "Forms are public pages the public fills in: enquiries that become Sales leads, event registrations and customer surveys. You start from Blank, Enquiry, Event registration or Customer feedback, in English or Arabic, and build it from cards with twenty question types, sections and branching. Answers are encrypted at rest, and the Responses tab counts them, lists every reply and downloads a CSV. A scale question shows its average, and a recommend score shows a Net Promoter Score.",
           ar: "النماذج صفحات عامة يملؤها الجمهور: استفسارات تتحول إلى عملاء محتملين للمبيعات، وتسجيلات في فعاليات، واستبيانات للعملاء. تبدأ من نموذج فارغ أو استفسار أو تسجيل فعالية أو رأي العملاء، بالعربية أو الإنجليزية، وتبنيه من بطاقات بعشرين نوعا من الأسئلة مع أقسام وتفرعات. تشفر الإجابات عند حفظها، ويحصيها تبويب الردود ويعرض كل رد وينزل ملف CSV. ويعرض سؤال المقياس متوسطه، وسؤال احتمال التوصية صافي نقاط الترويج." },
      keywords: ["form", "survey", "registration", "enquiry", "nps", "نموذج", "استبيان", "تسجيل", "استفسار", "صافي نقاط الترويج"],
      related: ["marketing-forms.create", "marketing-forms.share"] },
    { id: "marketing-forms.create", topic: "dept.marketing-forms", kind: "howto", open: "marketing-forms",
      q: { en: "How do I build and open a form?", ar: "كيف أبني نموذجا وأفتحه للجمهور؟" },
      a: { en: "A form is a draft until opened, and its address shows nothing to the public until then. Each question's type can be changed with its dropdown, cards are dragged to reorder, and Preview shows the real public page beside the editor. A form takes answers while Open and until the end of its closing date, if it has one. Editing a form needs the right to edit forms.",
           ar: "النموذج مسودة حتى يفتح، ولا يعرض عنوانه شيئا للجمهور قبل ذلك. يمكن تغيير نوع كل سؤال من قائمته المنسدلة، وسحب البطاقات لإعادة ترتيبها، وتعرض المعاينة الصفحة العامة الحقيقية بجانب المحرر. يستقبل النموذج الإجابات ما دام مفتوحا وحتى نهاية تاريخ إغلاقه إن وجد. ويحتاج تعديل النموذج إلى صلاحية تعديل النماذج." },
      steps: { en: ["Open Forms and choose a template.", "Give it a name and a language.", "Add, change and reorder questions on the Questions tab.", "In Settings, map the name, company, phone and email answers and set what an answer sets off.", "Set who can answer to Open."],
               ar: ["افتح النماذج واختر قالبا.", "أعطه اسما ولغة.", "أضف الأسئلة وغيرها ورتبها في تبويب الأسئلة.", "في الإعدادات اربط إجابات الاسم والشركة والهاتف والبريد وحدد ما تطلقه الإجابة.", "اجعل خيار من يمكنه الإجابة مفتوحا."] },
      keywords: ["build form", "new form", "publish form", "questions", "بناء نموذج", "نموذج جديد", "نشر النموذج", "أسئلة"],
      related: ["marketing-forms.cannot-open", "marketing-forms.rules"] },
    { id: "marketing-forms.cannot-open", topic: "dept.marketing-forms", kind: "troubleshoot", common: true, open: "marketing-forms",
      q: { en: "Why can't I open (publish) my form?", ar: "لماذا لا أستطيع فتح نموذجي للجمهور؟" },
      a: { en: "Opening is refused while anything would stop the form working: it has no question to answer; it makes Sales leads and no answer is mapped to a phone or email, or none to a name or company; or it collects contact details and has no required Consent question. An open form's edits are held to the same rules. A form with responses cannot be deleted either; close it instead.",
           ar: "يرفض الفتح ما دام هناك ما يمنع النموذج من العمل: لا يوجد سؤال للإجابة؛ أو ينشئ عملاء محتملين للمبيعات ولا توجد إجابة مربوطة بهاتف أو بريد، أو لا شيء مربوط باسم أو شركة؛ أو يجمع بيانات اتصال دون سؤال موافقة مطلوب. وتخضع تعديلات النموذج المفتوح للقواعد نفسها. كما لا يمكن حذف نموذج له ردود، بل يغلق بدلا من ذلك." },
      keywords: ["cannot publish", "consent question", "form refused", "delete form", "لا يمكن النشر", "سؤال الموافقة", "حذف النموذج"],
      related: ["marketing-forms.create", "marketing-audiences.about"] },
    { id: "marketing-forms.share", topic: "dept.marketing-forms", kind: "howto", open: "marketing-forms",
      q: { en: "How do I share a form or put it on our website?", ar: "كيف أشارك نموذجا أو أضعه على موقعنا؟" },
      a: { en: "A form's public address is the studio's slug plus a random code, so a form nobody was given cannot be found; it shows the studio's name and logo and is not indexed by search engines. Settings offers three ways to share it: the link with a Copy button, a QR code to show or download for flyers and stands, and an embed code for any website.",
           ar: "العنوان العام للنموذج هو معرف الاستوديو مع رمز عشوائي، فلا يمكن العثور على نموذج لم يعط لأحد؛ ويعرض اسم الاستوديو وشعاره ولا تفهرسه محركات البحث. وتعرض الإعدادات ثلاث طرق للمشاركة: الرابط مع زر نسخ، ورمز QR للعرض أو التنزيل للمطويات والأجنحة، وشيفرة تضمين لأي موقع إلكتروني." },
      steps: { en: ["Make sure the form is Open.","Open its Settings and find the sharing options.","Copy the link, download the QR code, or copy the embed code and paste it into your website."],
               ar: ["تأكد من أن النموذج مفتوح.","افتح إعداداته وابحث عن خيارات المشاركة.","انسخ الرابط، أو نزل رمز QR، أو انسخ شيفرة التضمين والصقها في موقعك."] },
      keywords: ["share", "qr code", "embed", "website", "iframe", "مشاركة", "رابط", "رمز QR", "تضمين", "موقع إلكتروني"],
      related: ["marketing-forms.about"] },
    { id: "marketing-forms.rules", topic: "dept.marketing-forms", kind: "settings", open: "marketing-forms",
      q: { en: "How do form answers become Sales leads?", ar: "كيف تتحول إجابات النموذج إلى عملاء محتملين للمبيعات؟" },
      a: { en: "In Settings, what an answer sets off is a list of rules: when a question has an answer, raise a Sales lead and optionally hand it to a person. The first rule that holds wins, and an answer matching no rule is simply kept. Naming a person needs the right to assign leads. The lead carries the form's campaign, or the campaign on the link the person arrived by. Rules that do anything other than raise a lead are not available yet.",
           ar: "في الإعدادات، ما تطلقه الإجابة قائمة قواعد: عندما يكون لسؤال إجابة معينة، أنشئ عميلا محتملا للمبيعات وسلمه اختياريا لشخص. تسري أول قاعدة تتحقق، والإجابة التي لا تطابق أي قاعدة تحفظ فقط. وتسمية شخص تحتاج إلى صلاحية إسناد العملاء المحتملين. ويحمل العميل المحتمل حملة النموذج، أو الحملة الموجودة في الرابط الذي وصل منه الشخص. والقواعد التي تفعل شيئا غير إنشاء عميل محتمل غير متاحة بعد." },
      keywords: ["lead rules", "create lead", "routing", "assign", "قواعد العملاء المحتملين", "إنشاء عميل محتمل", "توجيه"],
      related: ["crm-sales-tickets.assign-lead"] },
    { id: "marketing-forms.files", topic: "dept.marketing-forms", kind: "troubleshoot", open: "marketing-forms",
      q: { en: "Why does my form refuse file uploads?", ar: "لماذا يرفض نموذجي رفع الملفات؟" },
      a: { en: "A file question accepts only the kinds and number of files it declares, each up to 1, 2 or 4 MB, and the form must be open. Each form also has an overall allowance of 100, 500 or 2000 MB, shown in Settings; once it is full, the form stops taking files and says so.",
           ar: "يقبل سؤال الملف الأنواع وعدد الملفات المحددة له فقط، بحجم 1 أو 2 أو 4 ميغابايت لكل ملف، ويجب أن يكون النموذج مفتوحا. ولكل نموذج أيضا سعة إجمالية تبلغ 100 أو 500 أو 2000 ميغابايت تظهر في الإعدادات، وعند امتلائها يتوقف النموذج عن قبول الملفات ويذكر ذلك." },
      keywords: ["upload", "file too big", "attachment", "storage", "رفع ملف", "ملف كبير", "مرفق", "السعة"],
      related: ["marketing-forms.about"] },

    // ---- Budget & spend ----------------------------------------------------
    { id: "marketing-budget.about", topic: "dept.marketing-budget", kind: "about", common: true, open: "marketing-budget",
      q: { en: "What does Budget & spend show?", ar: "ماذا تعرض شاشة الميزانية والإنفاق؟" },
      a: { en: "It puts each campaign's budget beside what Finance recorded against it, then says what the money bought: cost per lead, cost per won deal, return on spend and net. A campaign is nearly spent from 80% of its budget and over past 100%, and the list puts those first. A sub-campaign's spend counts inside its parent's. The screen is view only; nothing is spent from Marketing.",
           ar: "تضع ميزانية كل حملة بجانب ما سجلته المالية عليها، ثم تبين ما اشتراه المال: تكلفة العميل المحتمل، وتكلفة الصفقة الرابحة، والعائد على الإنفاق، والصافي. تعد الحملة قريبة من النفاد عند 80% من ميزانيتها ومتجاوزة بعد 100%، وتظهر هذه أولا في القائمة. ويحتسب إنفاق الحملة الفرعية ضمن حملتها الأم. والشاشة للعرض فقط؛ فلا ينفق شيء من التسويق." },
      keywords: ["budget", "spend", "cost per lead", "roi", "overspend", "الميزانية", "الإنفاق", "تكلفة العميل المحتمل", "العائد", "تجاوز الميزانية"],
      related: ["marketing-budget.file-cost", "marketing-budget.no-spend"] },
    { id: "marketing-budget.file-cost", topic: "dept.marketing-budget", kind: "howto", common: true, open: "marketing-budget",
      q: { en: "How do I record money spent on a campaign?", ar: "كيف أسجل مبلغا أنفق على حملة؟" },
      a: { en: "A cost is a bill or an expense raised in Finance that names the campaign; there is no second way to record spend in Marketing. Only open campaigns are offered. Re-filing a cost against another campaign does not re-open its approval. Setting the budget itself is editing the campaign.",
           ar: "التكلفة فاتورة أو مصروف يسجل في المالية ويذكر الحملة؛ ولا توجد طريقة ثانية لتسجيل الإنفاق في التسويق. تعرض الحملات المفتوحة فقط. وإعادة نسب التكلفة إلى حملة أخرى لا تعيد فتح اعتمادها. أما ضبط الميزانية نفسها فهو تعديل للحملة." },
      steps: { en: ["Open Finance, Payables & Expenses.", "Raise the bill or expense as usual.", "Choose the campaign in the campaign field (beside the cost code on a bill, beside the project on an expense).", "Save; the cost appears on Budget & spend."],
               ar: ["افتح المالية، الدائنون والمصروفات.", "سجل الفاتورة أو المصروف كالمعتاد.", "اختر الحملة في حقل الحملة (بجانب رمز التكلفة في الفاتورة، وبجانب المشروع في المصروف).", "احفظ؛ فتظهر التكلفة في الميزانية والإنفاق."] },
      keywords: ["record spend", "bill", "expense", "campaign cost", "تسجيل الإنفاق", "فاتورة", "مصروف", "تكلفة الحملة"],
      related: ["marketing-budget.no-spend"] },
    { id: "marketing-budget.no-spend", topic: "dept.marketing-budget", kind: "troubleshoot", open: "marketing-budget",
      q: { en: "Why does a campaign show less spend than I expect?", ar: "لماذا تظهر الحملة إنفاقا أقل مما أتوقع؟" },
      a: { en: "Only bills and expenses naming the campaign count; Draft and Cancelled bills do not, though an unapproved bill does. Spend is read only when Payables & Expenses is switched on, and the screen says when it is not. What has been ordered on a purchase order but not yet invoiced is not counted, because a purchase order cannot name a campaign yet. A bill in a currency that cannot be converted is left out and counted separately.",
           ar: "لا يحتسب إلا الفواتير والمصروفات التي تذكر الحملة؛ ولا تحتسب الفواتير المسودة والملغاة، بينما تحتسب الفاتورة غير المعتمدة. ولا يقرأ الإنفاق إلا إذا كان قسم الدائنين والمصروفات مفعلا، وتذكر الشاشة ذلك إن لم يكن. وما طلب في أمر شراء ولم يفوتر بعد لا يحتسب، لأن أمر الشراء لا يمكنه ذكر حملة بعد. والفاتورة بعملة لا يمكن تحويلها تستبعد وتعد على حدة." },
      keywords: ["missing spend", "committed", "purchase order", "currency", "إنفاق ناقص", "ملتزم به", "أمر شراء", "عملة"],
      related: ["marketing-budget.file-cost"] },
    { id: "marketing-budget.alerts", topic: "dept.marketing-budget", kind: "troubleshoot", open: "marketing-budget",
      q: { en: "Will anyone be alerted when a campaign goes over budget?", ar: "هل ينبه أحد عندما تتجاوز الحملة ميزانيتها؟" },
      a: { en: "Not yet. The screen marks campaigns as over or nearly spent, but nobody is notified. Spend over time, month by month, and budgets per period are not available either; a campaign's budget is one number for its whole life.",
           ar: "ليس بعد. تعلم الشاشة الحملات المتجاوزة أو القريبة من النفاد، لكن لا يرسل تنبيه لأحد. كما لا يتوفر الإنفاق عبر الزمن شهرا بشهر ولا الميزانيات حسب الفترة؛ فميزانية الحملة رقم واحد طوال عمرها." },
      keywords: ["alert", "notification", "over budget", "monthly spend", "تنبيه", "إشعار", "تجاوز الميزانية", "الإنفاق الشهري"],
      related: ["marketing-budget.about"] },

    // ---- Planning & calendar -----------------------------------------------
    { id: "marketing-planning.about", topic: "dept.marketing-planning", kind: "about", common: true, open: "marketing-planning",
      q: { en: "What does the marketing calendar show?", ar: "ماذا يعرض تقويم التسويق؟" },
      a: { en: "The calendar draws a bar for each campaign across whole weeks starting on Monday, twelve weeks by default, coloured by status; events are drawn as markers. Above it, it lists what starts and ends this week and warns when one channel carries more than one campaign in the same week. Cancelled campaigns are left off, and campaigns with no start date are named underneath. Month and quarter views, printing and export are not available yet.",
           ar: "يرسم التقويم شريطا لكل حملة عبر أسابيع كاملة تبدأ يوم الاثنين، اثني عشر أسبوعا افتراضيا، ملونا حسب الحالة، وتظهر الفعاليات كعلامات. وفوقه يسرد ما يبدأ وما ينتهي هذا الأسبوع وينبه عندما تحمل قناة واحدة أكثر من حملة في الأسبوع نفسه. تستبعد الحملات الملغاة، وتذكر الحملات بلا تاريخ بدء أسفله. ولا تتوفر بعد عروض الشهر والربع ولا الطباعة والتصدير." },
      keywords: ["calendar", "schedule", "timeline", "overlap", "تقويم", "جدول", "خط زمني", "تداخل"],
      related: ["marketing-planning.move", "marketing-planning.plans"] },
    { id: "marketing-planning.move", topic: "dept.marketing-planning", kind: "troubleshoot", open: "marketing-campaigns",
      q: { en: "Why can't I drag a campaign to new dates on the calendar?", ar: "لماذا لا أستطيع سحب حملة إلى تواريخ جديدة في التقويم؟" },
      a: { en: "The calendar changes nothing, by design. A campaign's dates are edited in the campaign register, one click from every bar, and that needs the right to edit campaigns.",
           ar: "لا يغير التقويم شيئا، وهذا مقصود. تعدل تواريخ الحملة في سجل الحملات، وهو على بعد نقرة من كل شريط، ويحتاج ذلك إلى صلاحية تعديل الحملات." },
      keywords: ["drag", "change dates", "reschedule", "سحب", "تغيير التواريخ", "إعادة الجدولة"],
      related: ["marketing-planning.about"] },
    { id: "marketing-planning.plans", topic: "dept.marketing-planning", kind: "howto", common: true, open: "marketing-planning",
      q: { en: "How do I create a marketing plan for a month or quarter?", ar: "كيف أنشئ خطة تسويق لشهر أو ربع سنة؟" },
      a: { en: "A plan is a name, a period, what the period is for, a budget envelope and targets for leads and revenue. Choose Month, Quarter, Half year or Year and any day inside it, and the plan covers the whole period; Custom takes two dates. The plan shows its budget, what was handed to its campaigns, what is not yet allocated, what Finance recorded as spent and what remains, and measures its targets against its campaigns. The plan's owner is notified.",
           ar: "الخطة اسم وفترة وغرض الفترة وسقف ميزانية وأهداف للعملاء المحتملين والإيراد. اختر شهرا أو ربعا أو نصف سنة أو سنة وأي يوم داخلها، فتغطي الخطة الفترة كاملة، أو اختر مخصصا لتحديد تاريخين. تعرض الخطة ميزانيتها وما وزع على حملاتها وما لم يوزع بعد وما سجلته المالية كإنفاق وما تبقى، وتقيس أهدافها مقابل حملاتها. ويبلغ مسؤول الخطة." },
      steps: { en: ["Open Planning & calendar and go to the plans tab.", "Create a plan: name, period, purpose, budget and targets.", "File campaigns under it from the plan, or in the campaign's own form."],
               ar: ["افتح التخطيط والتقويم وانتقل إلى تبويب الخطط.", "أنشئ خطة: الاسم والفترة والغرض والميزانية والأهداف.", "انسب الحملات إليها من الخطة، أو من نموذج الحملة نفسها."] },
      keywords: ["plan", "quarterly plan", "annual plan", "budget envelope", "خطة", "خطة ربع سنوية", "خطة سنوية", "سقف الميزانية"],
      related: ["marketing-planning.file-campaign"] },
    { id: "marketing-planning.file-campaign", topic: "dept.marketing-planning", kind: "troubleshoot", open: "marketing-planning",
      q: { en: "Why isn't a campaign counted in my plan?", ar: "لماذا لا تحتسب حملة ضمن خطتي؟" },
      a: { en: "A campaign belongs to a plan only when it names the plan; nothing is inferred from dates, because a campaign across two quarters would otherwise count twice. Every plan lists the live campaigns inside its dates that belong to no plan, with a button to file each. Filing needs the right to edit campaigns. A plan cannot be deleted while a campaign names it.",
           ar: "لا تنتمي الحملة إلى خطة إلا إذا ذكرت الخطة؛ ولا يستنتج شيء من التواريخ، وإلا لاحتسبت الحملة الممتدة عبر ربعين مرتين. وتسرد كل خطة الحملات الجارية ضمن تواريخها التي لا تنتمي إلى أي خطة، مع زر لنسب كل منها. ويحتاج النسب إلى صلاحية تعديل الحملات. ولا يمكن حذف خطة ما دامت حملة تذكرها." },
      keywords: ["file campaign", "unfiled", "delete plan", "نسب الحملة", "غير منسوبة", "حذف الخطة"],
      related: ["marketing-planning.plans"] },

    // ---- Audiences & consent -----------------------------------------------
    { id: "marketing-audiences.about", topic: "dept.marketing-audiences", kind: "about", common: true, open: "marketing-audiences",
      q: { en: "What is the consent ledger?", ar: "ما هو سجل الموافقات؟" },
      a: { en: "The consent ledger records who agreed to be contacted, by email or by phone (phone covers calls, SMS and WhatsApp together). Entries come from a ticked consent question on a Marketing form, or are recorded by hand. The latest decision for an address wins, and never asked is its own answer, not a no. The addresses are encrypted at rest, and the wording they agreed to is kept as evidence.",
           ar: "يسجل سجل الموافقات من وافق على التواصل معه، بالبريد أو بالهاتف (ويشمل الهاتف المكالمات والرسائل النصية وواتساب معا). تأتي القيود من سؤال موافقة محدد في نموذج تسويق، أو تسجل يدويا. يسري آخر قرار للعنوان، و«لم يسأل قط» إجابة مستقلة وليست رفضا. تشفر العناوين عند حفظها، ويحفظ النص الذي وافقوا عليه كدليل." },
      keywords: ["consent", "opt-in", "gdpr", "permission to contact", "unsubscribe", "موافقة", "الاشتراك", "إذن التواصل", "إلغاء الاشتراك"],
      related: ["marketing-audiences.record", "marketing-audiences.append-only"] },
    { id: "marketing-audiences.record", topic: "dept.marketing-audiences", kind: "howto", common: true, open: "marketing-audiences",
      q: { en: "How do I record that someone agreed or withdrew consent?", ar: "كيف أسجل موافقة شخص أو سحبه لها؟" },
      a: { en: "Record it by hand for somebody who wrote in, telephoned, signed a sheet at a stand or asked to be left alone; you need the right to edit audiences. The date may be backdated but never set in the future. A backdated entry may change nothing, because the latest decision wins, and the screen tells you the state the address now holds.",
           ar: "سجلها يدويا لمن راسلك أو اتصل أو وقع على ورقة في جناح أو طلب عدم التواصل معه؛ وتحتاج إلى صلاحية تعديل الجماهير. يمكن أن يكون التاريخ سابقا لكن لا يكون في المستقبل. وقد لا يغير القيد ذو التاريخ السابق شيئا، لأن آخر قرار هو الساري، وتخبرك الشاشة بالحالة الحالية للعنوان." },
      steps: { en: ["Open Audiences & consent.", "Add an entry with the email or phone number.", "Choose whether consent was given or withdrawn, and the date.", "Save and check the state the screen reports."],
               ar: ["افتح الجماهير والموافقات.", "أضف قيدا بالبريد الإلكتروني أو رقم الهاتف.", "اختر هل منحت الموافقة أو سحبت، والتاريخ.", "احفظ وتحقق من الحالة التي تعرضها الشاشة."] },
      keywords: ["withdraw consent", "opt out", "do not contact", "record consent", "سحب الموافقة", "عدم التواصل", "تسجيل موافقة"],
      related: ["marketing-audiences.append-only"] },
    { id: "marketing-audiences.append-only", topic: "dept.marketing-audiences", kind: "troubleshoot", open: "marketing-audiences",
      q: { en: "Why can't I edit or delete a consent entry?", ar: "لماذا لا أستطيع تعديل قيد موافقة أو حذفه؟" },
      a: { en: "The ledger is append-only: nothing can be changed or removed, on the screen or anywhere else. A consent somebody could change afterwards proves nothing. To reverse a decision, add a new entry; the latest one wins. Erasing everything held about an address is not available yet.",
           ar: "السجل للإضافة فقط: لا يمكن تغيير أي شيء أو حذفه، لا من الشاشة ولا من غيرها. فالموافقة التي يمكن تغييرها لاحقا لا تثبت شيئا. ولعكس قرار أضف قيدا جديدا، والأخير هو الساري. ومسح كل ما يحفظ عن عنوان ما غير متاح بعد." },
      keywords: ["edit consent", "delete consent", "erasure", "mistake", "تعديل الموافقة", "حذف الموافقة", "مسح البيانات", "خطأ"],
      related: ["marketing-audiences.record"] },
    { id: "marketing-audiences.not-yet", topic: "dept.marketing-audiences", kind: "troubleshoot", open: "marketing-audiences",
      q: { en: "Can I build mailing lists or segments, or let people manage their own preferences?", ar: "هل يمكنني بناء قوائم مراسلة أو شرائح، أو السماح للأشخاص بإدارة تفضيلاتهم؟" },
      a: { en: "Not yet. Lists and segments, importing contacts in bulk, separate consent per channel on a form, and a public preference centre are not available. Since nompany sends nothing, nothing checks the ledger before a send yet; it is the record you will need when sending arrives.",
           ar: "ليس بعد. القوائم والشرائح واستيراد جهات الاتصال دفعة واحدة والموافقة المنفصلة لكل قناة في النموذج ومركز التفضيلات العام غير متاحة. وبما أن nompany لا يرسل شيئا، فلا شيء يتحقق من السجل قبل الإرسال حاليا؛ فهو السجل الذي ستحتاجه عندما يتوفر الإرسال." },
      keywords: ["mailing list", "segment", "import contacts", "preference centre", "قائمة مراسلة", "شريحة", "استيراد جهات الاتصال", "مركز التفضيلات"],
      related: ["marketing.not-sending"] },

    // ---- Events & webinars -------------------------------------------------
    { id: "marketing-events.about", topic: "dept.marketing-events", kind: "about", common: true, open: "marketing-events",
      q: { en: "How do events work, and where are the registrations?", ar: "كيف تعمل الفعاليات، وأين التسجيلات؟" },
      a: { en: "An event names a registration form, and its sign-ups are that form's replies, counted where Forms keeps them; an event without a form has nothing to count. What the event itself stores is attendance: who came, the turnout and who did not. Upcoming, on now and finished follow the event's start and end. Capacity is information only, and an oversubscribed event shows how many over it is.",
           ar: "تذكر الفعالية نموذج تسجيل، والمسجلون فيها هم ردود ذلك النموذج محسوبة حيث تحفظها النماذج؛ والفعالية بلا نموذج لا يوجد ما تحصيه. أما ما تحفظه الفعالية نفسها فهو الحضور: من حضر ونسبة الحضور ومن لم يحضر. وتتبع حالات القادمة والجارية والمنتهية وقت بدء الفعالية وانتهائها. والسعة معلومة فقط، وتعرض الفعالية التي زاد المسجلون فيها عن سعتها مقدار الزيادة." },
      keywords: ["event", "webinar", "registration", "attendance", "capacity", "فعالية", "ندوة", "تسجيل", "حضور", "السعة"],
      related: ["marketing-events.fields", "marketing-events.attendance"] },
    { id: "marketing-events.fields", topic: "dept.marketing-events", kind: "fields", common: true, open: "marketing-events",
      q: { en: "What do I need to create an event?", ar: "ما الذي أحتاجه لإنشاء فعالية؟" },
      a: { en: "Only a name is essential to start; the rest describes the event. Leave capacity blank for no limit; a capacity of zero is refused. Create a registration form in Forms first if you want to count sign-ups.",
           ar: "الاسم وحده ضروري للبدء، والباقي يصف الفعالية. اترك السعة فارغة لعدم وضع حد، والسعة صفر مرفوضة. وأنشئ نموذج تسجيل في النماذج أولا إذا أردت إحصاء المسجلين." },
      fields: { en: ["Name and description", "Kind: in person or online", "Start, and an optional end", "Place: an address or a joining link", "Capacity (blank for no limit)", "Owner", "Campaign and registration form (optional)"],
                ar: ["الاسم والوصف", "النوع: حضوري أو عبر الإنترنت", "وقت البدء، ووقت انتهاء اختياري", "المكان: عنوان أو رابط انضمام", "السعة (فارغة لعدم وضع حد)", "المسؤول", "الحملة ونموذج التسجيل (اختياري)"] },
      keywords: ["new event", "create webinar", "venue", "joining link", "فعالية جديدة", "إنشاء ندوة", "المكان", "رابط الانضمام"],
      related: ["marketing-forms.create"] },
    { id: "marketing-events.attendance", topic: "dept.marketing-events", kind: "howto", open: "marketing-events",
      q: { en: "How do I mark who attended an event?", ar: "كيف أحدد من حضر الفعالية؟" },
      a: { en: "Marking attendance is editing the event, so you need the right to edit events. You tick the registrations who came, and the whole list is saved at once. Somebody who turns up unregistered cannot be marked, because attendance is keyed to registrations, and there is no check-in from a phone yet.",
           ar: "تحديد الحضور تعديل للفعالية، فتحتاج إلى صلاحية تعديل الفعاليات. تحدد المسجلين الذين حضروا، وتحفظ القائمة كلها دفعة واحدة. ولا يمكن تحديد من حضر دون تسجيل، لأن الحضور مرتبط بالتسجيلات، ولا يتوفر بعد تسجيل الحضور من الهاتف." },
      steps: { en: ["Open the event.", "Tick each registration who attended.", "Save the list."],
               ar: ["افتح الفعالية.", "حدد كل مسجل حضر.", "احفظ القائمة."] },
      keywords: ["attendance", "check-in", "turnout", "no-show", "الحضور", "تسجيل الحضور", "نسبة الحضور", "لم يحضر"],
      related: ["marketing-events.registrants"] },
    { id: "marketing-events.registrants", topic: "dept.marketing-events", kind: "troubleshoot", open: "marketing-events",
      q: { en: "Why can't I see the names of people who registered?", ar: "لماذا لا أرى أسماء المسجلين؟" },
      a: { en: "Registrants' names, emails and phone numbers are form answers, so they are shown only to somebody who may view that form's responses. The event right opens the counts and the turnout, not the people. The screen says so rather than showing an empty list.",
           ar: "أسماء المسجلين وبريدهم وهواتفهم إجابات نموذج، لذلك لا تعرض إلا لمن يحق له عرض ردود ذلك النموذج. وصلاحية الفعاليات تتيح الأعداد ونسبة الحضور لا الأشخاص. وتذكر الشاشة ذلك بدلا من عرض قائمة فارغة." },
      keywords: ["registrants hidden", "no names", "permissions", "المسجلون مخفيون", "لا أسماء", "صلاحيات"],
      related: ["marketing-events.about"] },
    { id: "marketing-events.not-yet", topic: "dept.marketing-events", kind: "troubleshoot", open: "marketing-events",
      q: { en: "Can nompany send event invitations or reminders, or keep a waiting list?", ar: "هل يرسل nompany دعوات أو تذكيرات للفعاليات، أو يحتفظ بقائمة انتظار؟" },
      a: { en: "Not yet. No invitation, reminder or calendar invitation is sent beyond the form's own confirmation message, and there is no waiting list: the form keeps accepting replies when capacity is reached. Recurring events, sessions, speakers and agendas are not available either. An event that has already run, or has anyone marked as attending, cannot be deleted.",
           ar: "ليس بعد. لا ترسل دعوة أو تذكير أو دعوة تقويم سوى رسالة التأكيد الخاصة بالنموذج، ولا توجد قائمة انتظار: يستمر النموذج في قبول الردود عند بلوغ السعة. ولا تتوفر كذلك الفعاليات المتكررة والجلسات والمتحدثون وجداول الأعمال. ولا يمكن حذف فعالية جرت أو فيها من حدد حضوره." },
      keywords: ["invitation", "reminder", "waiting list", "waitlist", "delete event", "دعوة", "تذكير", "قائمة انتظار", "حذف الفعالية"],
      related: ["marketing.not-sending"] },

    // ---- Content & brand assets --------------------------------------------
    { id: "marketing-content.about", topic: "dept.marketing-content", kind: "about", common: true, open: "marketing-content",
      q: { en: "What is the Content & brand assets library?", ar: "ما هي مكتبة المحتوى وأصول العلامة؟" },
      a: { en: "It holds what was made for your marketing: artwork, copy, video, logos and documents, each with a name, a kind, notes, a version label, a file and optionally a campaign. Assets are grouped by campaign, and those belonging to no campaign, such as the brand logo, are shown first. Files are stored privately and served only to members. There is no preview, folders, tags, search or approval yet.",
           ar: "تضم ما صنع لتسويقك: التصاميم والنصوص والفيديو والشعارات والوثائق، ولكل منها اسم ونوع وملاحظات وتسمية إصدار وملف وحملة اختيارية. تجمع الأصول حسب الحملة، وتظهر أولا الأصول التي لا تتبع حملة مثل شعار العلامة. تحفظ الملفات بشكل خاص ولا تقدم إلا للأعضاء. ولا تتوفر بعد المعاينة والمجلدات والوسوم والبحث والاعتماد." },
      keywords: ["assets", "brand", "logo", "artwork", "library", "أصول", "العلامة التجارية", "شعار", "تصاميم", "مكتبة"],
      related: ["marketing-content.upload", "marketing-content.version"] },
    { id: "marketing-content.upload", topic: "dept.marketing-content", kind: "howto", common: true, open: "marketing-content",
      q: { en: "How do I add an asset?", ar: "كيف أضيف أصلا؟" },
      a: { en: "You need the right to create content. The file is set once, when the asset is created; to change it, add a new version rather than replacing the file.",
           ar: "تحتاج إلى صلاحية إنشاء المحتوى. يحدد الملف مرة واحدة عند إنشاء الأصل؛ ولتغييره أضف إصدارا جديدا بدلا من استبدال الملف." },
      steps: { en: ["Open Content & brand assets.", "Add an asset and give it a name.", "Choose its kind: artwork, copy, video, logo, document or other.", "Optionally choose a campaign and a version label, and add notes.", "Upload the file and save."],
               ar: ["افتح المحتوى وأصول العلامة.", "أضف أصلا وأعطه اسما.", "اختر نوعه: تصميم أو نص أو فيديو أو شعار أو وثيقة أو غير ذلك.", "اختر حملة وتسمية إصدار اختياريا، وأضف ملاحظات.", "ارفع الملف واحفظ."] },
      keywords: ["upload", "add asset", "new file", "رفع", "إضافة أصل", "ملف جديد"],
      related: ["marketing-content.version"] },
    { id: "marketing-content.version", topic: "dept.marketing-content", kind: "howto", open: "marketing-content",
      q: { en: "How do I replace an asset with a newer version?", ar: "كيف أستبدل أصلا بإصدار أحدث؟" },
      a: { en: "Upload the new file as its own asset, then mark it as replacing the older one; the old file stays and stays readable, so you can always see which version was used. Marking a replacement is an edit. The replacement must itself be current, and nothing is replaced twice. A new version may belong to a different campaign, for artwork reworked for another season.",
           ar: "ارفع الملف الجديد كأصل مستقل، ثم حدده كبديل للأصل الأقدم؛ ويبقى الملف القديم متاحا للقراءة، فيمكنك دائما معرفة الإصدار الذي استخدم. وتحديد البديل يعد تعديلا. ويجب أن يكون البديل نفسه حاليا، ولا يستبدل أصل مرتين. ويمكن أن يتبع الإصدار الجديد حملة مختلفة، كتصميم أعيد إعداده لموسم آخر." },
      steps: { en: ["Add the new file as a new asset.","Open the older asset.","Mark it as replaced by the new one and save."],
               ar: ["أضف الملف الجديد كأصل جديد.","افتح الأصل الأقدم.","حدده كمستبدل بالأصل الجديد واحفظ."] },
      keywords: ["new version", "replace file", "update logo", "إصدار جديد", "استبدال الملف", "تحديث الشعار"],
      related: ["marketing-content.delete"] },
    { id: "marketing-content.delete", topic: "dept.marketing-content", kind: "troubleshoot", open: "marketing-content",
      q: { en: "Why can't I delete an asset?", ar: "لماذا لا أستطيع حذف أصل؟" },
      a: { en: "An asset in a version chain cannot be deleted at either end: removing the old one destroys the history, and removing its replacement leaves the older one replaced by nothing. A loose asset, uploaded by mistake, can be deleted, and its file goes with it. An asset whose campaign was deleted is not lost; it moves to the unattached group.",
           ar: "لا يمكن حذف أصل ضمن سلسلة إصدارات من أي طرف: فحذف القديم يمحو السجل، وحذف بديله يترك القديم مستبدلا بلا شيء. أما الأصل المنفرد المرفوع خطأ فيمكن حذفه ويحذف ملفه معه. والأصل الذي حذفت حملته لا يضيع بل ينتقل إلى مجموعة غير المرتبطة." },
      keywords: ["delete asset", "remove file", "version chain", "حذف أصل", "حذف الملف", "سلسلة الإصدارات"],
      related: ["marketing-content.version"] },

    // ---- Partners & influencers --------------------------------------------
    { id: "marketing-partners.about", topic: "dept.marketing-partners", kind: "about", common: true, open: "marketing-partners",
      q: { en: "How does the partners register count what a partner brought in?", ar: "كيف يحسب سجل الشركاء ما جلبه الشريك؟" },
      a: { en: "A partner owns the utm_source tag on the links they publish. When somebody reaches one of your forms through such a link, the arrival is counted for that partner, along with the leads, won deals and their value it became. The figures are counted, never typed in. Tags arriving that no partner holds are listed too, commonest first, which is often the partner you did not know you had. Only form arrivals are counted.",
           ar: "يملك الشريك وسم utm_source في الروابط التي ينشرها. وعندما يصل أحدهم إلى أحد نماذجك عبر هذا الرابط يحتسب الوصول لذلك الشريك، مع العملاء المحتملين والصفقات الرابحة وقيمتها التي نتجت عنه. تحسب الأرقام ولا تكتب يدويا. وتسرد أيضا الوسوم الواردة التي لا يملكها أي شريك، الأكثر تكرارا أولا، وكثيرا ما تكشف شريكا لم تكن تعرفه. ولا يحتسب إلا الوصول عبر النماذج." },
      keywords: ["partner", "influencer", "affiliate", "referral", "utm_source", "شريك", "مؤثر", "تسويق بالعمولة", "إحالة"],
      related: ["marketing-partners.add", "marketing-partners.no-figures"] },
    { id: "marketing-partners.add", topic: "dept.marketing-partners", kind: "fields", common: true, open: "marketing-partners",
      q: { en: "What do I need to add a partner?", ar: "ما الذي أحتاجه لإضافة شريك؟" },
      a: { en: "Only the name and kind are required, because you often record who you are talking to long before there is a tag or a fee. Two partners may not hold the same tag, and tags match regardless of capitals. The fee is a note in words; what a partner actually costs is a Finance bill naming the campaign, and commission payouts are not available yet.",
           ar: "الاسم والنوع وحدهما مطلوبان، لأنك كثيرا ما تسجل من تتحدث إليه قبل وجود وسم أو أتعاب بوقت طويل. ولا يجوز لشريكين حمل الوسم نفسه، وتطابق الوسوم دون اعتبار لحالة الأحرف. الأتعاب ملاحظة نصية، أما التكلفة الفعلية للشريك ففاتورة في المالية تذكر الحملة، وصرف العمولات غير متاح بعد." },
      fields: { en: ["Name (required)", "Kind: partner, agency, influencer, affiliate or other (required)", "Their tag (utm_source)", "Contact name, email, phone and website", "What was agreed, in words", "Notes and an owner", "Whether the arrangement is still running"],
                ar: ["الاسم (مطلوب)", "النوع: شريك أو وكالة أو مؤثر أو مسوق بالعمولة أو غير ذلك (مطلوب)", "الوسم الخاص به (utm_source)", "اسم جهة الاتصال والبريد والهاتف والموقع الإلكتروني", "ما تم الاتفاق عليه كتابة", "ملاحظات ومسؤول", "هل الترتيب ما زال قائما"] },
      keywords: ["add partner", "new influencer", "agency", "commission", "إضافة شريك", "مؤثر جديد", "وكالة", "عمولة"],
      related: ["marketing-partners.about"] },
    { id: "marketing-partners.no-figures", topic: "dept.marketing-partners", kind: "troubleshoot", open: "marketing-partners",
      q: { en: "Why does a partner show no figures?", ar: "لماذا لا تظهر أرقام لشريك ما؟" },
      a: { en: "A partner with no tag shows no figures, and the screen says why: nobody has given them a link yet. Only arrivals at a form through a link carrying their tag are counted, so people they send to another page or by telephone do not show. Figures are not split by campaign either. The win rate stays empty until a lead has arrived.",
           ar: "الشريك الذي لا وسم له لا تظهر له أرقام، وتذكر الشاشة السبب: لم يعطه أحد رابطا بعد. ولا يحتسب إلا الوصول إلى نموذج عبر رابط يحمل وسمه، فلا يظهر من يرسلهم إلى صفحة أخرى أو عبر الهاتف. كما لا تقسم الأرقام حسب الحملة. وتبقى نسبة الفوز فارغة حتى يصل عميل محتمل." },
      keywords: ["no figures", "zero leads", "tag", "tracking", "لا أرقام", "صفر عملاء", "وسم", "تتبع"],
      related: ["marketing-campaigns.tracked-link"] },
    { id: "marketing-partners.delete", topic: "dept.marketing-partners", kind: "troubleshoot", open: "marketing-partners",
      q: { en: "Why can't I delete a partner?", ar: "لماذا لا أستطيع حذف شريك؟" },
      a: { en: "A partner that brought anybody is kept, because the arrivals carrying their tag are the record of what the arrangement was worth. Mark the arrangement as ended instead. A partner that brought nobody can be deleted.",
           ar: "يحتفظ بالشريك الذي جلب أي أحد، لأن حالات الوصول التي تحمل وسمه هي سجل قيمة الترتيب. حدد الترتيب كمنته بدلا من ذلك. أما الشريك الذي لم يجلب أحدا فيمكن حذفه." },
      keywords: ["delete partner", "end partnership", "حذف شريك", "إنهاء الشراكة"],
      related: ["marketing-partners.about"] },
  ],
};
