"use client";
import { useState } from "react";
import { motion, useReducedMotion } from "motion/react";
import { useLandingLocale } from "@/components/landing/locale";
import { landingDict } from "@/shared/landing";
import { EASE_OUT_EXPO } from "@/components/landing/lib/motion";
/* ==================================================================
   TECHNIQUE 7b — Shape morphing
   Framer Motion interpolates the numbers inside a `d` string, so two
   paths morph smoothly **iff they share an identical command
   structure**. Hand-written blobs almost never do, so both shapes are
   generated by the same function from a radius array: same M, same N
   cubic segments, same Z → guaranteed morphable.

   Generation happens at module scope with no randomness, so server and
   client render byte-identical markup (no hydration mismatch).
================================================================== */
/** Closed Catmull-Rom spline through N polar points, emitted as cubics. */
function blobPath(radii, cx = 100, cy = 100) {
    const n = radii.length;
    const r2 = (v) => Math.round(v * 100) / 100;
    const pts = radii.map((r, i) => {
        const a = (i / n) * Math.PI * 2 - Math.PI / 2;
        return [cx + Math.cos(a) * r, cy + Math.sin(a) * r];
    });
    let d = `M ${r2(pts[0][0])} ${r2(pts[0][1])}`;
    for (let i = 0; i < n; i += 1) {
        const p0 = pts[(i - 1 + n) % n];
        const p1 = pts[i];
        const p2 = pts[(i + 1) % n];
        const p3 = pts[(i + 2) % n];
        const c1x = p1[0] + (p2[0] - p0[0]) / 6;
        const c1y = p1[1] + (p2[1] - p0[1]) / 6;
        const c2x = p2[0] - (p3[0] - p1[0]) / 6;
        const c2y = p2[1] - (p3[1] - p1[1]) / 6;
        d += ` C ${r2(c1x)} ${r2(c1y)}, ${r2(c2x)} ${r2(c2y)}, ${r2(p2[0])} ${r2(p2[1])}`;
    }
    return `${d} Z`;
}
// Same arity → same path grammar → morphable.
const SHAPE_REST = blobPath([74, 60, 78, 62, 76, 58, 72, 64]);
const SHAPE_HOVER = blobPath([50, 82, 54, 80, 48, 84, 52, 78]);
const INNER_REST = blobPath([44, 36, 46, 34, 45, 35, 43, 38], 100, 100);
const INNER_HOVER = blobPath([32, 50, 30, 48, 34, 46, 31, 49], 100, 100);
export function MorphShape({ size = 240 }) {
    const reduceMotion = useReducedMotion();
    const [hovered, setHovered] = useState(false);
    const transition = { duration: 0.9, ease: EASE_OUT_EXPO };
    return (<div className="relative grid place-items-center" style={{ width: size, height: size }} onPointerEnter={() => setHovered(true)} onPointerLeave={() => setHovered(false)} 
    // Keyboard parity for the hover-only interaction
    onFocus={() => setHovered(true)} onBlur={() => setHovered(false)} tabIndex={0} role="img" aria-label={landingDict(useLandingLocale()).morphAlt}>
      <motion.svg viewBox="0 0 200 200" width={size} height={size} fill="none" animate={{ rotate: hovered ? 18 : 0, scale: hovered ? 1.04 : 1 }} transition={transition}>
        <defs>
          <linearGradient id="morph-grad" x1="0" y1="0" x2="200" y2="200">
            <stop offset="0%" stopColor="var(--color-iris)"/>
            <stop offset="55%" stopColor="var(--color-violet)"/>
            <stop offset="100%" stopColor="var(--color-cyan)"/>
          </linearGradient>
          <linearGradient id="morph-grad-2" x1="200" y1="0" x2="0" y2="200">
            <stop offset="0%" stopColor="var(--color-cyan)" stopOpacity="0.55"/>
            <stop offset="100%" stopColor="var(--color-iris)" stopOpacity="0.1"/>
          </linearGradient>
        </defs>

        {/* Outer blob: filled body */}
        <motion.path d={SHAPE_REST} fill="url(#morph-grad)" fillOpacity={0.16} stroke="url(#morph-grad)" strokeWidth="1.6" initial={{ d: SHAPE_REST }} animate={{ d: reduceMotion ? SHAPE_REST : hovered ? SHAPE_HOVER : SHAPE_REST }} transition={transition}/>

        {/* Inner blob counter-morphs for depth */}
        <motion.path d={INNER_REST} fill="url(#morph-grad-2)" initial={{ d: INNER_REST }} animate={{ d: reduceMotion ? INNER_REST : hovered ? INNER_HOVER : INNER_REST }} transition={{ ...transition, delay: 0.05 }}/>

        {/* Data nodes orbiting the shape */}
        {[0, 1, 2, 3].map((i) => {
            const angle = (i / 4) * Math.PI * 2;
            const rest = 86;
            const hover = 66;
            const r = hovered && !reduceMotion ? hover : rest;
            return (<motion.circle key={i} r="3.5" 
            // Base attributes = the rest state, so SSR markup is correct
            // and Framer has a real starting value to interpolate from.
            cx={100 + Math.cos(angle) * rest} cy={100 + Math.sin(angle) * rest} fill="var(--color-cyan)" initial={{
                    cx: 100 + Math.cos(angle) * rest,
                    cy: 100 + Math.sin(angle) * rest,
                    opacity: 0.6,
                }} animate={{
                    cx: 100 + Math.cos(angle) * r,
                    cy: 100 + Math.sin(angle) * r,
                    opacity: hovered ? 1 : 0.6,
                }} transition={{ ...transition, delay: i * 0.04 }}/>);
        })}
      </motion.svg>

      {/* Soft glow that intensifies on hover */}
      <motion.div aria-hidden className="pointer-events-none absolute inset-6 -z-10 rounded-full blur-3xl" style={{
            background: "radial-gradient(closest-side, color-mix(in oklab, var(--color-violet) 60%, transparent), transparent)",
        }} animate={{ opacity: hovered ? 0.7 : 0.35, scale: hovered ? 1.15 : 1 }} transition={transition}/>
    </div>);
}
