// THE L IN ETL — two sinks behind one interface, chosen by flag.
//
//   SqlFileSink   the DEFAULT / dry path. Renders transformed rows into batched
//                 INSERT statements in a .sql file. Needs no SQL Server and no
//                 driver, so it runs anywhere and produces the downloadable dump
//                 the brief asks for — without a live database to point at.
//
//   MssqlSink     the REAL load. Lazily imports `mssql` (not a dependency of this
//                 repo yet, so importing it is deferred to the moment it is
//                 actually used), opens ONE transaction per studio, inserts in
//                 batches, and MERGEs on the primary key so a re-run is idempotent
//                 and resumable. Behind an explicit --load flag; never the default.
//
// Both speak the same three methods: begin(studioId), write(table, rows),
// commit(studioId). The backfill drives them identically.

import { createWriteStream } from "node:fs";
import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";

// ---- rendering a JS value into a T-SQL literal -----------------------------
// The coercion tags from transform.mjs ({__sqlType}) tell us how to render.
// Strings are escaped by doubling the quote — the only escape T-SQL string
// literals need. NULL is a bare keyword, never a quoted "".
function literal(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "object" && v.__sqlType) {
    if (v.__sqlType === "datetime2") return `'${v.iso.replace("Z", "").replace("T", " ")}'`;
    if (v.__sqlType === "decimal") return String(v.value);
    if (v.__sqlType === "json") return `N'${JSON.stringify(v.value).replace(/'/g, "''")}'`;
  }
  return `N'${String(v).replace(/'/g, "''")}'`;
}

const BATCH = 500; // rows per INSERT ... VALUES — SQL Server's hard cap is 1000

export class SqlFileSink {
  constructor(path) {
    this.path = path;
    this.stream = null;
  }
  async open() {
    await mkdir(dirname(this.path), { recursive: true });
    this.stream = createWriteStream(this.path, { encoding: "utf8" });
    this.stream.write(
      "-- nompany Redis → SQL Server backfill export\n" +
        "-- Generated by scripts/migrate/backfill.mjs. Ids are preserved verbatim.\n" +
        "-- Schema (CREATE TABLE …) lives in docs/database-migration-mssql.md §2;\n" +
        "-- this file is DATA. Load the schema first, then run this.\n" +
        "SET NOCOUNT ON;\nSET XACT_ABORT ON;\n\n",
    );
  }
  // eslint-disable-next-line no-unused-vars
  async begin(studioId) {
    this.stream.write(`-- ── studio ${studioId} ──\nBEGIN TRAN;\n`);
  }
  async write(table, rows) {
    if (!rows.length) return;
    const cols = Object.keys(rows[0]);
    for (let i = 0; i < rows.length; i += BATCH) {
      const slice = rows.slice(i, i + BATCH);
      const values = slice.map((r) => `(${cols.map((c) => literal(r[c])).join(", ")})`).join(",\n  ");
      this.stream.write(`INSERT INTO dbo.[${table}] (${cols.map((c) => `[${c}]`).join(", ")}) VALUES\n  ${values};\n`);
    }
  }
  // eslint-disable-next-line no-unused-vars
  async commit(studioId) {
    this.stream.write("COMMIT TRAN;\n\n");
  }
  async close() {
    await new Promise((res) => this.stream.end(res));
  }
}

export class MssqlSink {
  constructor(config) {
    this.config = config; // { server, database, user, password, ... }
    this.sql = null;
    this.pool = null;
    this.tx = null;
  }
  async open() {
    // Deferred import: `mssql` is not installed in this repo, so importing it at
    // module top would break even the dry path. It is only needed here.
    this.sql = (await import("mssql")).default;
    this.pool = await this.sql.connect(this.config);
  }
  async begin() {
    this.tx = new this.sql.Transaction(this.pool);
    // One transaction per studio — a studio is the natural consistency and retry
    // unit (doc §4). A drop mid-studio rolls the whole studio back; the backfill's
    // MERGE-on-PK makes the retry a no-op for rows that already landed.
    await this._withRetry(() => this.tx.begin());
  }
  async write(table, rows) {
    if (!rows.length) return;
    // Batched, parameterised inserts via a table-valued request. Every value goes
    // through a parameter, never string interpolation — the injection surface the
    // .sql renderer avoids by escaping, this avoids by binding.
    const cols = Object.keys(rows[0]);
    for (let i = 0; i < rows.length; i += BATCH) {
      const slice = rows.slice(i, i + BATCH);
      const req = new this.sql.Request(this.tx);
      const tuples = slice
        .map((r, n) => `(${cols.map((c) => `@${c}_${n}`).join(", ")})`)
        .join(", ");
      slice.forEach((r, n) => cols.forEach((c) => req.input(`${c}_${n}`, this._bind(r[c]))));
      // MERGE so a re-run updates rather than duplicates — idempotent backfill.
      await this._withRetry(() =>
        req.query(
          `MERGE dbo.[${table}] AS t USING (VALUES ${tuples}) AS s (${cols.map((c) => `[${c}]`).join(", ")}) ` +
            `ON t.[${cols[0]}] = s.[${cols[0]}] WHEN NOT MATCHED THEN INSERT (${cols
              .map((c) => `[${c}]`)
              .join(", ")}) VALUES (${cols.map((c) => `s.[${c}]`).join(", ")});`,
        ),
      );
    }
  }
  async commit() {
    await this.tx.commit();
  }
  async close() {
    if (this.pool) await this.pool.close();
  }
  _bind(v) {
    if (v && typeof v === "object" && v.__sqlType) {
      if (v.__sqlType === "datetime2") return new Date(v.iso);
      if (v.__sqlType === "decimal") return v.value;
      if (v.__sqlType === "json") return JSON.stringify(v.value);
    }
    return v ?? null;
  }
  // A dropped connection self-heals on the next attempt; the doc calls for
  // "error handling for connection drops", and a small flat retry is the whole of
  // it — the same shape store.js uses, not exponential backoff.
  async _withRetry(fn, attempts = 4) {
    for (let i = 0; i < attempts; i++) {
      try {
        return await fn();
      } catch (e) {
        const transient = /ECONNRESET|ETIMEOUT|ESOCKET|Connection is closed/i.test(e?.message || "");
        if (!transient || i === attempts - 1) throw e;
        await new Promise((res) => setTimeout(res, 200));
      }
    }
  }
}
